# Occupational Gender Bias

Code, calculations, and plots accompanying the submission "Occupational gender bias in ungendered languages and LLMs: Comparing Hungarian and Chinese".

In [61]:
# Import libraries
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import ttest_ind
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.express as px

In [62]:
# Color scheme
# print(px.colors.qualitative.Pastel)

# Colors in RGB format for Plotly
# colors_in_rgb = ['rgb(102, 197, 204)', 'rgb(246, 207, 113)', 'rgb(248, 156, 116)', 'rgb(220, 176, 242)', 'rgb(135, 197, 95)', 'rgb(158, 185, 243)', 'rgb(254, 136, 177)', 'rgb(201, 219, 116)', 'rgb(139, 224, 164)', 'rgb(180, 151, 231)', 'rgb(179, 179, 179)']

# # Convert these into hex format for Plotly
# def rgb_to_hex(rgb):
#     return '#{:02x}{:02x}{:02x}'.format(*rgb)
# colors_in_hex = [rgb_to_hex(tuple(map(int, color[4:-1].split(',')))) for color in colors_in_rgb]
# colors_in_hex = ['#66c5cc', '#f6cf71','#f89c74','#dcb0f2','#87c55f','#9eb9f3','#fe88b1','#c9db74','#8be0a4','#b497e7','#b3b3b3']

# Custom colors
female_color = "#dcb0f2"
male_color = "#9eb9f3"
neutral_color = "#b3b3b3"

age_shades_hu = ['#f6b671', '#f89c74', '#f9826e', '#f6cf71']
age_shades_zh = ['#f6b671', '#f89c74', '#f9826e', '#f6cf71']

# Define colors for Hungarian and Chinese bars
hungarian_color = "#87c55f"  # greenish
chinese_color = "#c55f5f"  # reddish
hungarian_color_scale=["white", hungarian_color]
chinese_color_scale=["white", chinese_color]

## Occupations data

In [63]:
# Read files
occupations = pd.read_excel('occupations.xlsx')
occupations_for_clmm = occupations.copy()

# Remove r column
occupations = occupations.drop(columns=['r', '#_hu', '#_zh', 'item_hu', 'item_zh'])
occupations.head()

,service,en,hu,zh,lechat_hu,lechat_hu_std,copilot_hu,copilot_hu_std,chatgpt_hu,chatgpt_hu_std,...,lechat_zh,lechat_zh_std,copilot_zh,copilot_zh_std,chatgpt_zh,chatgpt_zh_std,deepseek_zh,deepseek_zh_std,gemini_zh,gemini_zh_std
0,NaN,model,modell,模特,1.0,0.781736,1.645,0.406510,2.150,0.275882,...,1.000,0.527046,2.09,0.372529,1.730,0.216282,1.45,0.158114,1.001,0.490044
1,NaN,soldier,katona,军人,-2.7,0.349603,-2.717,0.153119,-2.850,0.023570,...,-2.775,0.248607,-2.65,0.317105,-2.880,0.042164,-2.42,0.322490,-2.647,0.408848
2,NaN,pathologist,kórboncnok,法医,-1.5,0.942809,-1.545,0.312348,-1.147,0.206239,...,-0.600,0.737865,-1.19,0.292309,-1.560,0.231900,-1.25,0.263523,-0.973,0.248464
3,NaN,CEO,vezérigazgató,董事长,-1.6,0.459468,-2.377,0.320695,-2.130,0.067495,...,-2.330,0.380205,-2.51,0.341402,-1.990,0.191195,-1.70,0.230940,-2.028,0.415473
4,NaN,manager,menedzser,高管,-1.0,0.408248,-1.455,0.235478,-1.380,0.203033,...,-1.950,0.283823,-1.85,0.334166,-1.645,0.260821,-1.35,0.241523,-1.254,0.589618

In [64]:
# Remove rows where both item_hu AND item_zh are NOT 'in'
occupations_for_clmm = occupations_for_clmm[(occupations_for_clmm['item_hu'] == 'in') & (occupations_for_clmm['item_zh'] == 'in')]

# Count rows
occupations_for_clmm

,#_hu,#_zh,r,service,en,hu,item_hu,zh,item_zh,lechat_hu,...,lechat_zh,lechat_zh_std,copilot_zh,copilot_zh_std,chatgpt_zh,chatgpt_zh_std,deepseek_zh,deepseek_zh_std,gemini_zh,gemini_zh_std
0,1,11,0.859430,NaN,model,modell,in,模特,in,1.00,...,1.000,0.527046,2.09,0.372529,1.730,0.216282,1.45,0.158114,1.001,0.490044
1,2,37,0.387085,NaN,soldier,katona,in,军人,in,-2.70,...,-2.775,0.248607,-2.65,0.317105,-2.880,0.042164,-2.42,0.322490,-2.647,0.408848
2,3,33,0.031756,NaN,pathologist,kórboncnok,in,法医,in,-1.50,...,-0.600,0.737865,-1.19,0.292309,-1.560,0.231900,-1.25,0.263523,-0.973,0.248464
3,4,38,0.960823,NaN,CEO,vezérigazgató,in,董事长,in,-1.60,...,-2.330,0.380205,-2.51,0.341402,-1.990,0.191195,-1.70,0.230940,-2.028,0.415473
4,5,5,0.870006,NaN,manager,menedzser,in,高管,in,-1.00,...,-1.950,0.283823,-1.85,0.334166,-1.645,0.260821,-1.35,0.241523,-1.254,0.589618
6,7,27,0.212529,NaN,chef,szakács,in,厨师,in,-0.55,...,-1.250,0.353553,-1.04,0.309839,-1.650,0.236878,-1.68,0.239444,-1.912,0.480042
9,10,14,0.437662,NaN,accountant,könyvelő,in,会计,in,0.35,...,0.070,0.371334,1.00,0.461880,1.050,0.201384,0.50,0.333333,1.129,0.531966
10,11,3,0.698471,NaN,professor,professzor,in,教授,in,-0.90,...,-0.500,0.333333,-0.73,0.466786,-1.580,0.131656,-0.35,0.241523,-0.468,0.528915
11,12,50,0.370756,NaN,architect,építész,in,建筑师,in,-1.40,...,-1.100,0.699206,-1.22,0.415799,-2.170,0.115950,-1.78,0.248551,-1.965,0.296545
12,13,46,0.953608,NaN,scientist,tudós,in,科学家,in,-0.85,...,-0.800,0.483046,-1.31,0.213177,-1.930,0.149443,-0.85,0.241523,-1.254,0.413769
13,14,4,0.028937,NaN,nurse,ápoló,in,护士,in,1.25,...,2.200,0.258199,2.62,0.198886,2.770,0.048305,2.51,0.218327,2.386,0.420190
14,15,30,0.770146,NaN,cashier,pénztáros,in,收银员,in,1.35,...,0.900,0.737865,1.84,0.450185,2.095,0.111679,1.63,0.216282,1.443,0.416868
15,16,18,0.666812,NaN,judge,bíró,in,法官,in,-0.85,...,-0.800,0.483046,-1.16,0.302581,-1.490,0.191195,-0.20,0.258199,-0.688,0.415259
16,17,8,0.030419,NaN,worker,munkás,in,工人,in,-2.25,...,-2.250,0.263523,-1.61,0.185293,-1.900,0.133333,-1.80,0.421637,-1.076,0.281117
17,18,49,0.148003,NaN,lifeguard,vízimentő,in,救生员,in,-1.90,...,-2.330,0.298329,-1.33,0.362246,-1.320,0.274064,-1.58,0.293636,-1.389,0.503465
19,20,26,0.289903,NaN,ticket seller,jegyárus,in,售票员,in,0.25,...,0.150,0.337474,1.31,1.030049,0.940,0.211870,1.45,0.368932,1.132,0.283972
20,21,45,0.593638,NaN,firefighter,tűzoltó,in,消防员,in,-2.70,...,-2.775,0.248607,-2.61,0.303498,-2.855,0.076194,-2.43,0.340098,-3.000,0.000000
21,22,16,0.259661,NaN,engineer,mérnök,in,工程师,in,-1.90,...,-2.300,0.258199,-2.09,0.303498,-2.430,0.094868,-2.12,0.257337,-2.035,0.144318
23,24,36,0.401793,NaN,director,rendező,in,导演,in,-0.70,...,-1.250,0.353553,-1.66,0.333999,-1.720,0.225093,-1.78,0.248551,-1.857,0.343578
24,25,17,0.720763,NaN,cleaner,takarító,in,保洁,in,1.10,...,1.880,0.458984,2.23,0.312872,2.070,0.340098,1.78,0.248551,1.982,0.590476
25,26,43,0.759404,NaN,HR personnel,HR-es,in,人事,in,1.55,...,1.280,0.563323,1.62,0.352136,1.420,0.113529,1.56,0.157762,1.208,0.375701
26,27,29,0.238173,NaN,housekeeper,házvezető,in,家政员,in,1.70,...,2.605,0.180201,2.58,0.361478,2.810,0.056765,2.15,0.241523,2.468,0.437412
27,28,23,0.996989,NaN,flight attendant,légiutas-kísérő,in,乘务员,in,1.90,...,2.000,0.471405,1.52,0.644291,1.920,0.431535,1.00,0.912871,1.861,0.485671
28,29,21,0.102862,NaN,waiter,pincér,in,服务员,in,-1.05,...,0.320,0.473286,1.07,0.383116,0.770,0.221359,0.67,0.365300,1.008,0.250191
30,31,32,0.970634,NaN,doctor,orvos,in,医生,in,-0.60,...,-0.680,0.436654,-0.57,0.333500,-1.020,0.154919,-0.23,0.249666,-0.046,0.430715
31,32,24,0.417511,NaN,hairdresser,fodrász,in,理发师,in,1.00,...,-0.100,0.316228,1.21,0.486370,0.290,0.128668,-0.30,0.258199,0.005,0.770501
32,33,39,0.972258,NaN,farmer,földműves,in,农民,in,-2.10,...,-0.300,0.537484,-0.96,0.529570,-1.490,0.179196,-1.22,0.342540,-0.953,0.459324
34,35,12,0.942320,NaN,caregiver,gondozó,in,护工,in,2.00,...,1.800,0.537484,2.14,0.250333,2.430,0.125167,2.07,0.286938,1.610,0.741170
35,36,19,0.783193,NaN,shop assistant,bolti eladó,in,导购员,in,0.85,...,1.350,0.579751,1.72,0.364539,2.060,0.250333,1.68,0.239444,1.354,0.394608
36,37,41,0.744887,NaN,gardener,kertész,in,园丁,in,-1.25,...,-0.800,0.632456,-0.97,0.200278,-0.580,0.131656,-1.25,0.353553,-0.720,0.336782
37,38,2,0.410871,NaN,secretary,titkár,in,秘书,in,0.55,...,1.550,0.368932,2.17,0.235938,1.955,0.151749,2.10,0.316228,2.233,0.360248
39,40,28,0.343321,NaN,dietitian,dietetikus,in,营养师,in,1.70,...,1.350,0.529675,1.75,0.217307,2.350,0.212132,0.95,0.598609,1.227,0.327484
40,41,6,0.468609,NaN,teacher,tanár,in,教师,in,0.35,...,0.950,0.368932,0.95,0.283823,0.370,0.205751,1.45,0.158114,1.018,0.076129
41,42,1,0.518891,NaN,police officer,rendőr,in,警察,in,-2.05,...,-1.700,0.349603,-1.70,0.514242,-2.280,0.153116,-1.55,0.368932,-1.896,0.292848
42,43,42,0.822661,NaN,pilot,pilóta,in,飞行员,in,-2.05,...,-2.580,0.175119,-2.35,0.374907,-2.530,0.125167,-2.06,0.302581,-2.278,0.368504
44,45,7,0.390466,NaN,receptionist,recepciós,in,前台,in,1.65,...,1.700,0.483046,2.23,0.221359,2.460,0.157762,1.95,0.158114,2.027,0.242581
45,46,35,0.762541,NaN,security guard,biztonsági őr,in,保安,in,-2.45,...,-2.625,0.212459,-2.18,0.229976,-2.735,0.100139,-2.00,0.235702,-2.408,0.452936
46,47,48,0.110504,NaN,prosecutor,ügyész,in,检察官,in,-1.35,...,-0.600,0.737865,-1.38,0.311983,-1.675,0.220164,-0.25,0.353553,-0.881,0.370359
47,48,20,0.176446,NaN,beautician,kozmetikus,in,美容师,in,2.65,...,2.605,0.180201,2.65,0.395109,2.875,0.054006,2.35,0.241523,2.569,0.433447
48,49,34,0.894726,NaN,programmer,programozó,in,程序员,in,-1.90,...,-2.250,0.263523,-2.18,0.301109,-2.370,0.125167,-2.10,0.210819,-2.244,0.332104
49,50,40,0.483495,NaN,student,diák,in,学生,in,0.00,...,0.000,0.000000,0.00,0.000000,0.000,0.000000,0.00,0.000000,0.000,0.000000

## Hungarian data

In [65]:
# # Read Hungarian participant data from prolific_hu.csv
# df_prolific_hu = pd.read_csv('prolific_hu.csv')

# # Return Participant of rows where Status is RETURNED or REJECTED
# rejects = df_prolific_hu[df_prolific_hu['Status'].isin(['RETURNED', 'REJECTED'])]['Participant'].unique()

# # create reject list
# rejects_list = rejects.tolist()
# print(f"Rejected participants: {rejects_list}")

# # Check
# df_prolific_hu.head()

In [66]:
# Read Hungarian data from hu.xlsx
df_hu = pd.read_excel('ratings_hu.xlsx')

# # Define the mapping for ratings if not already mapped
# rating_map = {
#     1: -3,
#     2: -2,
#     3: -1,
#     4: 0,
#     5: 1,
#     6: 2,
#     7: 3
# }

# # Get columns to convert (skip non-rating columns)
# rating_columns = df_zh.columns[4:]  # assuming first 8 columns are not ratings

# # Replace and explicitly infer objects to avoid warning
# for col in rating_columns:
#     df_zh[col] = df_zh[col].map(rating_map)

# Replace férfi to male and nő to female in Gender column
df_hu['Gender'] = df_hu['Gender'].replace({'férfi': 'male', 'nő': 'female'})

# Rename ID to participant
df_hu.rename(columns={'ID': 'Participant'}, inplace=True)

# Print number of participants
print(f"Number of participants: {df_hu.shape[0]}")

Number of participants: 99

In [67]:
# Filtering those who failed attention checks
hu_attention_checks = ['pincérnő','titkárnő','tanárnő','takarítónő','ápolónő','házvezetőnő']

# boolean: True where response != '3' (a failure)
failures = df_hu[hu_attention_checks].astype(str).ne('3')

# count failures per participant
failed_counts = failures.sum(axis=1)

# participants who failed at least 2 checks
failed_participants = df_hu.loc[failed_counts >= 2, 'Participant'].unique().tolist()

# optional: view rows of those participants
removed_rows = df_hu.loc[failed_counts >= 2, ['Participant'] + hu_attention_checks]

# remove them from the dataframe
df_hu_clean = df_hu[~df_hu['Participant'].isin(failed_participants)].reset_index(drop=True)

# quick feedback
if failed_participants:
    print(f"{len(failed_participants)} participants failed >=2 attention checks:")
    print(failed_participants)
else:
    print("No participants failed >=2 attention checks.")
    
# Remove failed_participants from df_hu
df_hu = df_hu[~df_hu['Participant'].isin(failed_participants)].reset_index(drop=True)   


# Drop attention checks
df_hu.drop(columns=hu_attention_checks, inplace=True)

########################################################################
# Remove column with missing values (removes 'lawyer' and 'politician')!
df_hu.dropna(axis=1, inplace=True)

# Show the cleaned dataframe
df_hu

16 participants failed >=2 attention checks:
[13, 27, 29, 32, 39, 41, 57, 59, 61, 63, 69, 75, 91, 92, 94, 98]

,Participant,Age,Gender,modell,katona,kórboncnok,vezérigazgató,menedzser,nővér,szakács,...,dietetikus,tanár,rendőr,pilóta,recepciós,biztonsági őr,ügyész,kozmetikus,programozó,diák
0,1,25-35,male,2,-3,0,-1,-1,3,0,...,0,0,-2,-1,0,-2,0,2,-1,0
1,2,45-55,male,2,-2,-1,-1,0,3,0,...,0,0,-2,-2,1,-2,-1,3,-2,0
2,3,25-35,male,0,-2,0,-1,-1,2,-1,...,0,0,-1,0,0,-2,0,2,0,0
3,4,35-45,male,2,-2,-1,-1,0,3,-1,...,1,2,-2,-2,2,-2,-1,3,-2,0
4,5,25-35,male,0,-2,-2,0,0,3,-1,...,0,0,-1,-1,0,-1,0,2,-2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,93,25-35,male,2,-2,-1,-2,-1,2,0,...,1,-1,-1,-2,1,-1,-1,3,-1,0
79,95,35-45,male,1,-2,-1,-2,-1,2,-1,...,0,1,-1,-2,0,-2,-2,3,-1,0
80,96,25-35,male,1,-2,-3,-1,-1,3,-2,...,1,0,-2,-2,1,-3,0,2,-3,0
81,97,35-45,female,2,-2,-1,-2,-2,2,-2,...,1,0,-1,-1,1,-2,-2,3,-2,0
82,99,35-45,male,2,-2,0,-1,-3,2,0,...,2,1,0,-2,1,-3,0,3,-3,0

### Demographics

In [68]:
color_map = {
    'Men': female_color,
    'Women': male_color,
    'Equal': neutral_color
}

# Three shades of teal for age groups
gender_colors = [female_color, male_color]

# Prepare gender and age counts and percentages
gender_counts = df_hu['Gender'].value_counts()
gender_labels = gender_counts.index
gender_labels_en = ['Male' if g == 'male' else 'Female' for g in gender_labels]
gender = gender_counts / gender_counts.sum() * 100

age_counts = df_hu['Age'].value_counts().sort_index()
age = age_counts / age_counts.sum() * 100

# Gender pie with custom colors
gender_pie = go.Pie(
    labels=gender_labels_en,
    values=gender.values,
    name='Gender',
    hole=0.33,
    title='Gender',
    marker=dict(colors=gender_colors),
    customdata=np.stack([gender_labels_en, gender_counts.values, gender.values], axis=-1),
    textinfo='text',
    textfont=dict(size=28),
    text=[f"{label}<br>n={int(n)}<br>{p:.1f}%" for label, n, p in zip(gender_labels_en, gender_counts.values, gender.values)],
)

# Age pie with custom teal shades (repeat if more age groups)
age_pie = go.Pie(
    labels=age.index,
    values=age.values,
    name='Age',
    hole=0.33,
    title='Age',
    marker=dict(colors=age_shades_hu),
    customdata=np.stack([age.index, age_counts.values, age.values], axis=-1),
    textinfo='text',
    textfont=dict(size=28),
    text=[f"{label}<br>n={int(n)}<br>{p:.1f}%" for label, n, p in zip(age.index, age_counts.values, age.values)],
)

# Create subplot with 1 row and 2 columns
fig = make_subplots(
    rows=1, cols=2, specs=[[{'type':'domain'}, {'type':'domain'}]],
    subplot_titles=['Gender Distribution', 'Age Distribution']
)

fig.add_trace(gender_pie, 1, 1)
fig.add_trace(age_pie, 1, 2)

fig.update_layout(
    font = dict(family="Times New Roman, serif", size=32, color='black'),
    margin=dict(l=0, r=0, t=0, b=0),
    showlegend=False,
    legend=dict(
        font=dict(size=28),
        orientation='v',
        x=0.5,
        xanchor='center',
        y=1,
        yanchor='top'
    ),
    annotations=[
        dict(
            text=f'No. of participants: {df_hu.shape[0]}',
            x=0.5, y=0.9, xref='paper', yref='paper',
            showarrow=False, font=dict(size=28), align='center'
        )
    ]
)

fig.show()

# Save it as html
fig.write_html('demographics_hu.html')

# Save it as image
fig.write_image('demographics_hu.png', scale=3, width=1000, height=400)

### Analysis

In [69]:
# Prepare df_hu for clmm
df_hu_clmm = df_hu.copy()

# # Drop columns Start time and Completion time and Email and Name and Participant
# df_hu_clmm = df_hu_clmm.drop(columns=['Start time', 'Completion time', 'Email', 'Name', 'Participant'])

# Add a prefix to ID values to distinguish Hungarian participants
df_hu_clmm['Participant'] = 'hu_' + df_hu_clmm['Participant'].astype(str)

# Add a language column with value 'Hungarian'
df_hu_clmm['Language'] = 'Hungarian'

# Transform from wide to long format, with the items as index
df_hu_clmm = df_hu_clmm.melt(id_vars=['Participant', 'Age', 'Gender', 'Language'], var_name='Item', value_name='Rating')

# Add a new column that has the english translations ('en' column) by merging the dataframe with the 'occupations_for_clmm' dataframe's 'hu' column with the df_hu_clmm's 'Item' column and name it 'Occupation'
df_hu_clmm = df_hu_clmm.merge(occupations_for_clmm[['hu', 'en']], left_on='Item', right_on='hu', how='left')

# Rename 'hu' column to 'Occupation'
df_hu_clmm.rename(columns={'en': 'Occupation'}, inplace=True)

# Remove rows where 'Occupation' is 'nurse (sister)'
# df_hu_clmm = df_hu_clmm[df_hu_clmm['Occupation'] != 'nurse (sister)']

# Drop the 'hu' column
df_hu_clmm = df_hu_clmm.drop(columns=['hu'])

# Print number of unique items in df_hu_clmm
print("Number of unique occupations:", num_unique_items := df_hu_clmm['Occupation'].nunique())

# Show 
df_hu_clmm

Number of unique occupations: 41

     Participant    Age  Gender   Language    Item  Rating Occupation
0           hu_1  25-35    male  Hungarian  modell       2      model
1           hu_2  45-55    male  Hungarian  modell       2      model
2           hu_3  25-35    male  Hungarian  modell       0      model
3           hu_4  35-45    male  Hungarian  modell       2      model
4           hu_5  25-35    male  Hungarian  modell       0      model
...          ...    ...     ...        ...     ...     ...        ...
3647       hu_93  25-35    male  Hungarian    diák       0    student
3648       hu_95  35-45    male  Hungarian    diák       0    student
3649       hu_96  25-35    male  Hungarian    diák       0    student
3650       hu_97  35-45  female  Hungarian    diák       0    student
3651       hu_99  35-45    male  Hungarian    diák       0    student

[3652 rows x 7 columns]

In [70]:
# Define rating_columns as all columns except 'Participant', 'Age', 'Gender', and 'Occupation'
rating_columns_hu = [col for col in df_hu.columns if col not in ['Participant', 'Age', 'Gender', 'Occupation']]
rating_columns_hu

['modell',
 'katona',
 'kórboncnok',
 'vezérigazgató',
 'menedzser',
 'nővér',
 'szakács',
 'felszolgáló',
 'könyvelő',
 'professzor',
 'építész',
 'tudós',
 'ápoló',
 'pénztáros',
 'bíró',
 'munkás',
 'vízimentő',
 'jegyárus',
 'tűzoltó',
 'mérnök',
 'rendező',
 'takarító',
 'HR-es',
 'házvezető',
 'légiutas-kísérő',
 'pincér',
 'orvos',
 'fodrász',
 'földműves',
 'gondozó',
 'bolti eladó',
 'kertész',
 'titkár',
 'PR munkatárs',
 'dietetikus',
 'tanár',
 'rendőr',
 'pilóta',
 'recepciós',
 'biztonsági őr',
 'ügyész',
 'kozmetikus',
 'programozó',
 'diák']

#### Two-sample t-test by gender

In [71]:
# Add a new column with the mean of the ratings for each participant
df_hu['Mean Rating'] = df_hu.iloc[:, 4:].mean(axis=1)

# Separate df_hu into male and female datasets based on the Gender column
df_hu_male = df_hu[df_hu['Gender'] == 'male']
df_hu_female = df_hu[df_hu['Gender'] == 'female']

# Show the number of male and female participants
print(f"Number of male participants: {df_hu_male['Participant'].nunique()}")
print(f"Number of female participants: {df_hu_female['Participant'].nunique()}")

# Two Sample T-Test between male and female participants for each occupation word
results = []
for col in rating_columns_hu:
    male_ratings = df_hu_male[col].dropna().astype(float)
    female_ratings = df_hu_female[col].dropna().astype(float)
    # Only test if both groups have at least 2 ratings
    if len(male_ratings) > 1 and len(female_ratings) > 1:
        t_stat, p_value = stats.ttest_ind(male_ratings, female_ratings, equal_var=False)
        mean_male = male_ratings.mean()
        mean_female = female_ratings.mean()
        # Get English translation from occupations DataFrame
        en_translation = occupations.loc[occupations['hu'] == col, 'en'].values
        en_translation = en_translation[0] if len(en_translation) > 0 else ""
        results.append({
            'occupation': col,
            'mean_male': mean_male,
            'mean_female': mean_female,
            't_stat': t_stat,
            'p_value': p_value,
            # 'very_highly_significant': p_value is not None and p_value < 0.001,
            # 'highly_significant': p_value is not None and 0.001 <= p_value < 0.01,
            'significant': p_value is not None and p_value < 0.05,
            # 'marg_significant': p_value is not None and 0.05 < p_value < 0.1,
            'en': en_translation
        })

# Create a DataFrame from the results
df_ttest = pd.DataFrame(results)

# Add overall mean rating for sorting
df_ttest['overall_mean'] = (df_ttest['mean_male'] + df_ttest['mean_female']) / 2

# Sort by overall mean rating
df_ttest_sorted = df_ttest.sort_values('overall_mean', ascending=False)

# Prepare axis labels: bold for significant
def bold_label(row):
    occupation = row['occupation']
    # if row.get('very_highly_significant'):
    #     occupation = f"<b>{occupation}***</b>"
    # if row.get('highly_significant'):
    #     occupation = f"<b>{occupation}**</b>"
    if row.get('significant'):
        occupation = f"<b>{occupation}*</b>"
    # if row.get('marg_significant'):
    #     occupation = f"<b>{occupation}+</b>"
    return occupation

df_ttest_sorted['occupation_label'] = df_ttest_sorted.apply(bold_label, axis=1)

# Plot with English translation in hover
fig = go.Figure()

fig.add_trace(go.Bar(
    x=df_ttest_sorted['occupation_label'],
    y=df_ttest_sorted['mean_male'],
    name='Male',
    marker_color=male_color,
    customdata=df_ttest_sorted[['en']],
    hovertemplate='Occupation: %{x}<br>English: %{customdata[0]}<br>Mean (Male): %{y:.2f}<extra></extra>'
))

fig.add_trace(go.Bar(
    x=df_ttest_sorted['occupation_label'],
    y=df_ttest_sorted['mean_female'],
    name='Female',
    marker_color=female_color,
    customdata=df_ttest_sorted[['en']],
    hovertemplate='Occupation: %{x}<br>English: %{customdata[0]}<br>Mean (Female): %{y:.2f}<extra></extra>'
))

fig.update_layout(
    barmode='group',
    xaxis_tickangle=-45,
    yaxis_title='Bias (Male - Female)',
    yaxis=dict(
        range=[-3.1, 3.1],
        tickvals=[-3, -2, -1, 0, 1, 2, 3],
        title='Mean Rating (Bias)'
    ),
    template='plotly_white',
    font=dict(family="Times New Roman, serif", size=16, color='black'),
    margin=dict(l=0, r=0, t=0, b=0),
    legend=dict(
        orientation='h',
        yanchor='bottom',
        y=0,
        xanchor='center',
        x=0.5,
        bgcolor='rgba(220, 220, 220, 0.25)',
    )
)

# Show the plot
fig.show()

# Save it as HTML and image
fig.write_html('occupations_hu_gender.html')
fig.write_image('occupations_hu_gender.png', scale=3, width=1000, height=400)

Number of male participants: 45
Number of female participants: 38

#### Biases and biases by

In [72]:
# Add a column 'bias_by' to df_ttest_sorted: 'Male' if abs(mean_male) > abs(mean_female), 'Female' if abs(mean_female) > abs(mean_male), 'Equal' if they are the same
df_ttest_sorted['bias_by'] = np.where(
    np.abs(df_ttest_sorted['mean_male']) > np.abs(df_ttest_sorted['mean_female']), 'Men',
    np.where(np.abs(df_ttest_sorted['mean_male']) < np.abs(df_ttest_sorted['mean_female']), 'Women', 'Equal')
)

# Add columns that show if the bias is male or female. Add male, if the overall mean is lower than 0, othervise add Female
df_ttest_sorted['bias'] = np.where(
    df_ttest_sorted['overall_mean'] > 0, 'Female',
    np.where(df_ttest_sorted['overall_mean'] < 0, 'Male', 'Equal')
)

# Calculate mean_difference (mean_male - mean_female), and add its absolute value
df_ttest_sorted['mean_difference'] = (df_ttest_sorted['mean_male'] - df_ttest_sorted['mean_female']).abs()

#### Confusion matrix of biases

In [73]:
# Count unique values in 'bias' and 'bias_by' columns, ignoring 'Equal'
# Create confusion matrix, ignoring 'Equal'
conf_matrix_hu = pd.crosstab(
    df_ttest_sorted.loc[df_ttest_sorted['bias'] != 'Equal', 'bias'],
    df_ttest_sorted.loc[df_ttest_sorted['bias_by'] != 'Equal', 'bias_by']
)

# Plot confusion matrix with plotly
fig = go.Figure(data=go.Heatmap(
    z=conf_matrix_hu.values,
    x=conf_matrix_hu.columns,
    y=conf_matrix_hu.index,
    colorscale=hungarian_color_scale,
    text=conf_matrix_hu.values,
    texttemplate="%{text}",
    hovertemplate="Bias: %{y}<br>Bias By: %{x}<br>Count: %{z}<extra></extra>"
))

fig.update_layout(
    margin=dict(l=0, r=0, t=0, b=0),
    title="Confusion Matrix of Biases",
    xaxis_title="Bias By",
    yaxis_title="Bias",
    width=500,
    height=400
)

# Show
fig.show()

# Save confusion matrix as HTML and image
# fig.write_html('confusion_matrix_hu.html')
# fig.write_image('confusion_matrix_hu.png', scale=3, width=550, height=400)

#### Transpose

In [74]:
# Transpose results, a prepare a copy with only the ratings
df_hu_ratings = df_hu[rating_columns_hu].transpose()
df_hu = df_hu.transpose()

# # Remove rows with index: Participant, Start Time, Completion time, Email, Name
# df_hu = df_hu.drop(['Participant', 'Start time', 'Completion time', 'Email', 'Name'], axis=0) 

# Print number of rows
print(f"Number of rows: {len(df_hu_ratings)}")

# Sort by index
df_hu = df_hu.sort_index()

# Show
df_hu.head(10)

Number of rows: 44

,0,1,2,3,4,5,6,7,8,9,...,73,74,75,76,77,78,79,80,81,82
Age,25-35,45-55,25-35,35-45,25-35,25-35,35-45,45-55,25-35,35-45,...,45-55,<25,35-45,<25,25-35,25-35,35-45,25-35,35-45,35-45
Gender,male,male,male,male,male,male,female,female,male,male,...,female,female,male,female,female,male,male,male,female,male
HR-es,0,1,0,2,0,1,1,1,2,2,...,0,0,1,2,0,2,1,2,2,1
Mean Rating,-0.255814,-0.302326,-0.209302,0.232558,-0.209302,-0.186047,-0.395349,-0.232558,-0.209302,0.023256,...,-0.162791,-0.023256,-0.511628,-0.139535,-0.139535,-0.302326,-0.302326,-0.860465,-0.604651,-0.651163
PR munkatárs,0,0,0,1,0,0,1,-1,1,0,...,0,0,1,0,0,1,1,1,0,1
Participant,1,2,3,4,5,6,7,8,9,10,...,86,87,88,89,90,93,95,96,97,99
biztonsági őr,-2,-2,-2,-2,-1,-2,-2,-2,-2,-2,...,-2,-1,-3,-1,0,-1,-2,-3,-2,-3
bolti eladó,1,2,0,2,0,1,1,2,2,2,...,0,0,2,0,0,1,0,1,1,1
bíró,-1,0,0,-1,0,0,-1,0,0,1,...,0,1,-2,0,0,-1,1,-2,-2,0
dietetikus,0,0,0,1,0,1,2,1,1,1,...,0,0,1,0,0,1,0,1,1,2

#### One Sample T-test

In [75]:
# One Sample T-test with standard deviation
results = []

for index, row in df_hu_ratings.iterrows():
    ratings = row.dropna().astype(float)
    t_stat, p_value = stats.ttest_1samp(ratings, popmean=0)
    mean_rating = ratings.mean()
    std_rating = ratings.std()
    results.append({
        'item': index,  # item name from index
        'mean': mean_rating,
        'std': std_rating,
        't_stat': t_stat,
        'p_value': p_value,
        'significant': p_value < 0.05
    })

df_results = pd.DataFrame(results)

# Print significant results
print(df_results[df_results['significant']][['item', 'mean', 'std', 'p_value']])

# Filter for non-significant ratings
not_significant = df_results[~df_results['significant']]

# Get the min and max of the mean ratings where not significant
mean_min = not_significant['mean'].min()
mean_max = not_significant['mean'].max()

# Print the range of mean ratings where the rating is not significant
print(f"\nRange of mean ratings where the rating is not significant: {mean_min} to {mean_max}")

               item      mean       std       p_value
0            modell  1.084337  0.913380  1.865880e-17
1            katona -1.759036  0.758535  6.396149e-35
2        kórboncnok -0.975904  0.999706  1.172215e-13
3     vezérigazgató -1.265060  0.856600  1.857223e-22
4         menedzser -0.746988  0.921867  1.153452e-10
5             nővér  2.240964  0.835060  2.047581e-39
6           szakács -1.024096  0.826038  2.186931e-18
8          könyvelő  0.710843  0.862924  6.627569e-11
9        professzor -1.000000  0.937043  2.642355e-15
10          építész -1.156627  1.005860  8.623230e-17
11            tudós -0.674699  0.856943  2.957730e-10
12            ápoló  0.614458  1.197877  1.148601e-05
13        pénztáros  0.903614  0.864115  6.456069e-15
14             bíró -0.397590  0.936258  2.184064e-04
15           munkás -1.638554  1.042725  5.136908e-24
16        vízimentő -1.301205  1.020939  5.366343e-19
17         jegyárus  0.253012  0.809145  5.547307e-03
18          tűzoltó -2.144578  0.898950  8.868375e-36
19           mérnök -1.108434  0.924095  1.127779e-17
20          rendező -0.855422  0.813492  5.064698e-15
21         takarító  0.987952  1.338856  2.201366e-09
22            HR-es  1.192771  0.875936  1.652065e-20
23        házvezető  1.602410  1.188766  2.847530e-20
24  légiutas-kísérő  1.361446  0.994844  1.263333e-20
25           pincér -0.590361  1.048066  1.891416e-06
26            orvos -0.469880  0.721404  6.791973e-08
27          fodrász  0.915663  0.843986  1.264903e-15
28        földműves -1.626506  1.008632  1.109130e-24
29          gondozó  0.795181  1.123573  7.381584e-09
30      bolti eladó  0.759036  0.918514  5.950860e-11
31          kertész -0.939759  0.967136  1.414272e-13
33     PR munkatárs  0.554217  0.914024  3.808413e-07
34       dietetikus  0.771084  0.770260  4.150211e-14
36           rendőr -1.084337  0.886275  4.239196e-18
37           pilóta -1.530120  0.954289  1.558205e-24
38        recepciós  0.674699  0.797992  2.701484e-11
39    biztonsági őr -1.771084  0.941267  7.696904e-29
40           ügyész -0.650602  0.889419  2.850215e-09
41       kozmetikus  2.120482  0.915951  7.195553e-35
42       programozó -1.277108  0.966680  8.279418e-20

Range of mean ratings where the rating is not significant: -0.04819277108433735 to 0.10843373493975904

In [76]:
# Sort by mean for better readability
df_results_sorted = df_results.sort_values(by='mean')

# Create color labels
df_results_sorted['Significance'] = df_results_sorted['significant'].map({True: 'significant', False: 'not significant'})

# Plot
fig = px.bar(
    df_results_sorted,
    x='item',
    y='mean',
    color='Significance',
    color_discrete_map={'significant': 'crimson', 'not significant': 'lightgray'},
    title='One Sample T-test of Raw Ratings',
    labels={'item': 'Item', 'mean': 'Mean Rating'},
    # On hover, Show the item, mean rating, and p-value    
    hover_data=['item', 'mean', 'p_value'],
    # Edit hovertemplate to show item, mean, and p-value
    
)

fig.update_layout(
    xaxis_tickangle=-45,
    template='plotly_white',
    margin=dict(l=0, r=0, t=40, b=0),
    legend=dict(
        orientation='h',
        yanchor='bottom',
        y=0,
        xanchor='center',
        x=0.5,
        bgcolor='rgba(220, 220, 220, 0.25)',
    )
)

# Show
fig.show()

# # Save it as html
# fig.write_html('occupations_ttest_hu.html')
# fig.write_image('occupations_ttest_hu.png', scale=3, width=1000, height=400)

#### Merge ratings and occupations data

In [77]:
# Turn index column into a column called 'hu'
df_hu.reset_index(inplace=True)
df_hu.rename(columns={'index': 'hu'}, inplace=True)

# Merge df_hu and occupations on the 'hu' column
df_hu = pd.merge(df_hu, occupations, on='hu', how='left')

# Reorder columns so the dataframe starts with 'hu' 'en', 'zh', and so on
df_hu = df_hu[['hu', 'en', 'zh'] + [col for col in df_hu.columns if col not in ['hu', 'en' , 'zh']]]

# Merge df_hu and df_results on the 'hu' column
df_hu = pd.merge(df_hu, df_results, left_on='hu', right_on='item', how='left')

# Sort all occupations by their average ratings
df_hu = df_hu.sort_values(by='mean', ascending=False)

# Drop redundant columns
df_hu.drop(columns=['item', 't_stat'], inplace=True)

# Rename the columns for clarity
df_hu.rename(columns={'mean': 'mean_hu',
                      't_stat': 't_stat_hu',
                      'std': 'std_hu',
                      'p_value': 'p_value_hu',
                      'significant': 'significant_hu'}, inplace=True)


# Save df_hu as an Excel file
# df_hu.to_excel('occupations_hu.xlsx', index=False)

# Show the final DataFrame
df_hu.head()

#Show
df_hu.tail()

,hu,en,zh,0,1,2,3,4,5,6,...,chatgpt_zh,chatgpt_zh_std,deepseek_zh,deepseek_zh_std,gemini_zh,gemini_zh_std,mean_hu,std_hu,p_value_hu,significant_hu
42,tűzoltó,firefighter,消防员,-2,-3,0,-2,-2,-3,-2,...,-2.855,0.076194,-2.43,0.340098,-3.0,0.0,-2.144578,0.89895,8.868375e-36,True
0,Age,NaN,NaN,25-35,45-55,25-35,35-45,25-35,25-35,35-45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Gender,NaN,NaN,male,male,male,male,male,male,female,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mean Rating,NaN,NaN,-0.255814,-0.302326,-0.209302,0.232558,-0.209302,-0.186047,-0.395349,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Participant,NaN,NaN,1,2,3,4,5,6,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
# Show rating rows for student for checking
df_hu[df_hu['en'] == 'server'].iloc[:, 0:-12]

,hu,en,zh,0,1,2,3,4,5,6,...,copilot_hu,copilot_hu_std,chatgpt_hu,chatgpt_hu_std,deepseek_hu,deepseek_hu_std,gemini_hu,gemini_hu_std,lechat_zh,lechat_zh_std
11,felszolgáló,server,服务员 (2),0,-1,0,1,0,0,0,...,0.552,0.459754,0.545,0.197836,0.805,0.451202,0.427,0.400529,0.3,0.483046

In [79]:
# # Find duplicate values in the 'hu' column
# duplicates = df_hu['hu'][df_hu['hu'].duplicated(keep=False)]

# # Show duplicate rows
# duplicate_rows = df_hu[df_hu['hu'].isin(duplicates)]
# print("Duplicate rows in 'hu' column:")
# print(duplicate_rows[['hu', 'en', 'zh']])

# # # If there are duplicates, append (2) to the second and further occurrences
# # if not duplicates.empty:
# #     # Create a counter for each zh value
# #     zh_counts = {}
# #     def append_suffix(zh):
# #         count = zh_counts.get(zh, 0) + 1
# #         zh_counts[zh] = count
# #         if count > 1:
# #             return f"{zh}(2)"
# #         return zh
# #     df_zh['zh'] = df_zh['zh'].apply(append_suffix)

# # df_hu

# # If there are duplicates, remove the second one
# if not duplicates.empty:
#     # Create a mask for duplicates
#     mask = df_hu.duplicated(subset=['hu'], keep='first')
#     # Keep only the first occurrence of each duplicate
#     df_hu = df_hu[~mask]
# # Show the DataFrame after removing duplicates
# print("DataFrame after removing duplicates:")
# print(df_hu[['hu', 'en', 'zh']])

In [80]:
# Most agreement
# Get the top 5 words with the smallest standard deviation from df_hu
top_smallest_std = df_hu.nsmallest(5, 'std_hu')[['hu', 'en', 'std_hu']]
print(top_smallest_std)

             hu         en    std_hu
10         diák    student  0.312348
28        orvos     doctor  0.721404
17       katona    soldier  0.758535
9    dietetikus  dietitian  0.770260
11  felszolgáló     server  0.794856

#### Plot Ratings

In [81]:
# Make an explicit copy of the filtered DataFrame
df_hu_plot = df_hu[~df_hu['hu'].isin(['Age', 'Gender', 'Mean Rating'])].copy()

# Assign the 'bias' column safely
df_hu_plot.loc[:, 'bias'] = df_hu_plot['mean_hu'].apply(
    lambda x: 'Female' if x > mean_max else ('Male' if x < mean_min else 'Neutral')
)

color_map = {
    'Female': female_color, # '#e377c2', # pinkish
    'Male': male_color, # '#1f77b4', # blue
    'Neutral': neutral_color # gray
}

# Sort df_hu_plot by mean value before plotting
df_hu_plot_sorted = df_hu_plot.sort_values('mean_hu', ascending=False)

df_hu_plot_sorted['label_hu'] = df_hu_plot_sorted.apply(
    lambda row: f"{row['hu']} ({row['en']})" if pd.notna(row['en']) else row['hu'], axis=1
)

fig = go.Figure()

for bias in ['Female', 'Neutral', 'Male']:
    subset = df_hu_plot_sorted[df_hu_plot_sorted['bias'] == bias]
    fig.add_trace(go.Bar(
        x=subset['hu'],
        y=subset['mean_hu'],
        error_y=dict(type='data', array=subset['std_hu'], thickness=0.75),
        name=bias,
        marker_color=color_map[bias],
        hovertemplate=(
            'Hungarian: %{x}<br>'
            'Mean Rating: %{y:.2f}<br>'
            'Standard Deviation: %{error_y.array:.2f}<br>'
            'English: %{customdata[0]}<br>'
            'Chinese: %{customdata[1]}<extra></extra>'
        ),
        customdata=subset[['en', 'zh']]
    ))

fig.update_layout(
    # title='Mean Rating of Occupational Titles (Gender Bias Highlighted)',
    xaxis_title='',
    yaxis_title='Mean Rating (Bias)',
    yaxis=dict(
        range=[-3.1, 3.1],
        tickvals=[-3, -2, -1, 0, 1, 2, 3],
        title='Mean Rating (Bias)'
    ),
    xaxis_tickangle=-45,
    template='plotly_white',
    font = dict(family="Times New Roman, serif", size=16, color='black'),
    margin=dict(l=0, r=0, t=0, b=0),
    legend=dict(
        orientation='h',
        yanchor='bottom',
        y=0,
        xanchor='center',
        x=0.5,
        bgcolor='rgba(220, 220, 220, 0.25)',
    )
)

fig.show()

# Save this as a html and image
fig.write_html('occupations_hu.html')
fig.write_image('occupations_hu.png', scale=3, width=1000, height=400)

In [82]:
# Plot the Hungarian data with LLM reference lines using plotly.graph_objects (go)
fig = go.Figure()

# Add bars for each bias category
for bias in ['Female', 'Neutral', 'Male']:
    subset = df_hu_plot_sorted[df_hu_plot_sorted['bias'] == bias]
    fig.add_trace(go.Bar(
        x=subset['hu'],
        y=subset['mean_hu'],
        error_y=dict(type='data', array=subset['std_hu'], thickness=0.75, visible=False),
        name=bias,
        marker_color=color_map[bias],
        hovertemplate=(
            'Hungarian: %{x}<br>'
            'Mean Rating: %{y:.2f}<br>'
            # 'STD: %{error_y.array:.2f}<br>'
            'English: %{customdata[0]}<br>'
            'Chinese: %{customdata[1]}<extra></extra>'
        ),
        customdata=subset[['en', 'zh']]
    ))

# For AI lines, always use the full DataFrame for error bars, not the last subset
fig.add_trace(go.Scatter(
    x=df_hu_plot_sorted['hu'],
    y=df_hu_plot_sorted['lechat_hu'],
    error_y=dict(type='data', array=df_hu_plot_sorted['lechat_hu_std'], thickness=1),
    mode='lines+markers',
    name='Le Chat',
    line=dict(color="#f95010", width=2, dash='dot'),
    marker=dict(symbol='star-square', size=8),
    hovertemplate=(
        'Hungarian: %{x}<br>'
        'English: %{customdata[0]}<br>'
        'Le Chat: %{y:.2f}<br>'
        'STD: %{customdata[1]:.2f}<extra></extra>'
    ),
    customdata=df_hu_plot_sorted[['en', 'lechat_hu_std']]
))

fig.add_trace(go.Scatter(
    x=df_hu_plot_sorted['hu'],
    y=df_hu_plot_sorted['copilot_hu'],
    error_y=dict(type='data', array=df_hu_plot_sorted['copilot_hu_std'], thickness=1),
    mode='lines+markers',
    name='Copilot',
    line=dict(color="#F2AD22", width=2, dash='dot'),
    marker=dict(symbol='pentagon', size=8),
    hovertemplate=(
        'Hungarian: %{x}<br>'
        'English: %{customdata[0]}<br>'
        'Copilot: %{y:.2f}<br>'
        'STD: %{customdata[1]:.2f}<extra></extra>'
    ),
    customdata=df_hu_plot_sorted[['en', 'copilot_hu_std']]
))

fig.add_trace(go.Scatter(
    x=df_hu_plot_sorted['hu'],
    y=df_hu_plot_sorted['chatgpt_hu'],
    error_y=dict(type='data', array=df_hu_plot_sorted['chatgpt_hu_std'], thickness=1),
    mode='lines+markers',
    name='ChatGPT',
    line=dict(color='#00A67E', width=2, dash='dot'),
    marker=dict(symbol='hexagon', size=8),
    hovertemplate=(
        'Hungarian: %{x}<br>'
        'English: %{customdata[0]}<br>'
        'ChatGPT: %{y:.2f}<br>'
        'STD: %{customdata[1]:.2f}<extra></extra>'
    ),
    customdata=df_hu_plot_sorted[['en', 'chatgpt_hu_std']]
))

fig.add_trace(go.Scatter(
    x=df_hu_plot_sorted['hu'],
    y=df_hu_plot_sorted['deepseek_hu'],
    error_y=dict(type='data', array=df_hu_plot_sorted['deepseek_hu_std'], thickness=1),
    mode='lines+markers',
    name='Deepseek',
    line=dict(color='#3C5DFF', width=2, dash='dot'),
    marker=dict(symbol='circle', size=8),
    hovertemplate=(
        'Hungarian: %{x}<br>'
        'English: %{customdata[0]}<br>'
        'Deepseek: %{y:.2f}<br>'
        'STD: %{customdata[1]:.2f}<extra></extra>'
    ),
    customdata=df_hu_plot_sorted[['en', 'deepseek_hu_std']]
))

fig.add_trace(go.Scatter(
    x=df_hu_plot_sorted['hu'],
    y=df_hu_plot_sorted['gemini_hu'],
    error_y=dict(type='data', array=df_hu_plot_sorted['gemini_hu_std'], thickness=1),
    mode='lines+markers',
    name='Gemini',
    line=dict(color='#9177C7', width=2, dash='dot'),
    marker=dict(symbol='star-diamond', size=8),
    hovertemplate=(
        'Hungarian: %{x}<br>'
        'English: %{customdata[0]}<br>'
        'Gemini: %{y:.2f}<br>'
        'STD: %{customdata[1]:.2f}<extra></extra>'
    ),
    customdata=df_hu_plot_sorted[['en', 'gemini_hu_std']]
))

fig.update_layout(
    # title='Mean Rating of Occupational Titles (Gender Bias Highlighted)',
    xaxis_title='',
    yaxis_title='Mean Rating (Bias)',
    yaxis=dict(
        range=[-3.1, 3.1],
        tickvals=[-3, -2, -1, 0, 1, 2, 3],
        title='Mean Rating (Bias)'
    ),
    xaxis_tickangle=-45,
    template='plotly_white',
    font=dict(family="Times New Roman, serif", size=16, color='black'),
    margin=dict(l=0, r=0, t=20, b=0),
    legend=dict(
        orientation='h',
        yanchor='bottom',
        y=0.95,
        xanchor='center',
        x=0.5,
        bgcolor='rgba(220, 220, 220, 0.25)',
    )
)

fig.show()

# Save as HTML and image
fig.write_html('occupations_hu_with_ai.html')
fig.write_image('occupations_hu_with_ai.png', scale=3, width=1000, height=400)

#### AI agreement and variation

In [83]:
# Select only the relevant AI mean rating columns
ai_mean_cols = ['lechat_hu', 'copilot_hu', 'chatgpt_hu', 'deepseek_hu', 'gemini_hu']

# Calculate the standard deviation and range across AI models for each word
df_hu_plot_sorted['ai_std'] = df_hu_plot_sorted[ai_mean_cols].std(axis=1)
df_hu_plot_sorted['ai_range'] = df_hu_plot_sorted[ai_mean_cols].max(axis=1) - df_hu_plot_sorted[ai_mean_cols].min(axis=1)

In [84]:
import plotly.graph_objects as go

# Sort the full DataFrame by ai_std (lowest to highest)
df_ai_sorted = df_hu_plot_sorted.sort_values('ai_std')

# Prepare data for plotting
x_labels = df_ai_sorted['en']
hu_labels = df_ai_sorted['hu']
means = df_ai_sorted[['lechat_hu', 'copilot_hu', 'chatgpt_hu', 'deepseek_hu', 'gemini_hu']].values.T
models = ['Le Chat', 'Copilot', 'ChatGPT', 'Deepseek', 'Gemini']
colors = ['#f95010', '#F2AD22', '#00A67E', '#3C5DFF', '#9177C7']
markers = ['star-square', 'pentagon', 'hexagon', 'circle', 'star-diamond']

fig = go.Figure()

# Plot each model's mean as a scatter with markers (not lines)
for i, (model, color, marker) in enumerate(zip(models, colors, markers)):
    fig.add_trace(go.Scatter(
        x=x_labels,
        y=means[i],
        mode='markers',
        name=model,
        marker=dict(size=14, color=color, symbol=marker),
        customdata=np.stack([hu_labels], axis=-1),
        hovertemplate=f"{model}: %{{y:.2f}}<br>Occupation: %{{x}}<br>Hungarian: %{{customdata[0]}}"
    ))

# Add error bars for std
fig.add_trace(go.Bar(
    x=x_labels,
    y=df_ai_sorted['ai_std'],
    name='STD (AI models)',
    marker_color='gray',
    opacity=0.5,
    yaxis='y2',
    customdata=np.stack([hu_labels], axis=-1),
    hovertemplate='STD: %{y:.3f}<br>Occupation: %{x}<br>Hungarian: %{customdata[0]}'
))

# Add bar for range
fig.add_trace(go.Bar(
    x=x_labels,
    y=df_ai_sorted['ai_range'],
    name='Range (AI models)',
    marker_color='lightgray',
    opacity=0.5,
    yaxis='y2',
    customdata=np.stack([hu_labels], axis=-1),
    hovertemplate='Range: %{y:.3f}<br>Occupation: %{x}<br>Hungarian: %{customdata[0]}'
))

# Set up secondary y-axis for std and range
fig.update_layout(
    title='AI agent agreement and variation across Hungarian occupations',
    yaxis=dict(
        title='Mean Rating (Bias)',
        range=[-3.2, 3.2],
        tickvals=[-3, -2, -1, 0, 1, 2, 3]
    ),
    yaxis2=dict(
        title='STD / Range',
        overlaying='y',
        side='right',
        showgrid=False
    ),
    barmode='group',
    legend=dict(
        orientation='h',
        yanchor='bottom',
        y=1.025,
        xanchor='center',
        x=0.7
    ),
    template='plotly_white',
    margin=dict(l=0, r=0, t=0, b=0),
    font=dict(family="Times New Roman, serif", size=16, color='black'),
    xaxis_tickangle=45  # Rotate x-axis tick labels by 45 degrees
)

fig.show()

#### Correlation

In [85]:
# Calculate the absolute difference between human mean ratings and each AI model's mean ratings
ai_columns = ['lechat_hu', 'copilot_hu', 'chatgpt_hu', 'deepseek_hu', 'gemini_hu']
diffs = {}

# Calculate the absolute differences
for col in ai_columns:
    diffs[col] = (df_hu['mean_hu'] - df_hu[col]).abs()

# Create a DataFrame to summarize the mean absolute differences for each model
mean_diffs = {col: diffs[col].mean() for col in ai_columns}
mean_diffs_df = pd.DataFrame.from_dict(mean_diffs, orient='index', columns=['mean_absolute_difference'])
mean_diffs_df = mean_diffs_df.sort_values('mean_absolute_difference')

print("Mean absolute difference between human and AI model ratings (lower is closer):")
print(mean_diffs_df)

# Find the AI model with the smallest mean absolute difference
closest_model = mean_diffs_df.index[0]
print(f"\nThe AI model whose mean ratings are closest to human ratings is: {closest_model}")



# Plot
import plotly.figure_factory as ff
from scipy.stats import pearsonr

# Prepare correlation and p-value matrices as before
corr_cols = ['mean_hu', 'lechat_hu', 'copilot_hu', 'chatgpt_hu', 'deepseek_hu', 'gemini_hu']
df_corr = df_hu_plot[corr_cols].dropna()
corr_matrix = df_corr.corr(method='pearson')

# Compute p-value matrix
pval_matrix = pd.DataFrame(np.ones_like(corr_matrix), columns=corr_matrix.columns, index=corr_matrix.index)
for i in corr_matrix.columns:
    for j in corr_matrix.columns:
        if i == j:
            pval_matrix.loc[i, j] = 0.0
        else:
            r, p = pearsonr(df_corr[i], df_corr[j])
            pval_matrix.loc[i, j] = p

# Annotate with R and p
z_text = [[f"R={corr_matrix.iloc[i, j]:.2f}<br>p={pval_matrix.iloc[i, j]:.3g}" 
           for j in range(len(corr_matrix))] for i in range(len(corr_matrix))]

fig = ff.create_annotated_heatmap(
    z=corr_matrix.values,
    x=list(corr_matrix.columns),
    y=list(corr_matrix.index),
    annotation_text=z_text,
    colorscale=hungarian_color_scale,
    zmin=-1, zmax=1,
    showscale=True,
    colorbar=dict(title='Pearson R')
)

fig.update_layout(
    title='Correlation Matrix: Human vs AI Model Ratings',
    font=dict(family="Times New Roman, serif", size=12, color='black'),
    width=600, height=500,
    margin=dict(l=0, r=0, t=40, b=0)
)
fig.show()



# Table
# Prepare a DataFrame with R and p for each AI model vs mean_hu
correlation_results = pd.DataFrame({
    'AI Model': ai_columns,
    'R': [corr_matrix.loc['mean_hu', model] for model in ai_columns],
    'p_value': [pval_matrix.loc['mean_hu', model] for model in ai_columns]
})

# If P value is lower than 0.01, show < 0.01
correlation_results['p_value'] = correlation_results['p_value'].apply(lambda x: '< 0.01' if x < 0.01 else x)

# Sort it by R
correlation_results = correlation_results.sort_values(by='R', ascending=False)

print("Correlation Results:")
correlation_results

Mean absolute difference between human and AI model ratings (lower is closer):
             mean_absolute_difference
lechat_hu                    0.461665
gemini_hu                    0.639344
deepseek_hu                  0.708690
chatgpt_hu                   0.749542
copilot_hu                   0.753971

The AI model whose mean ratings are closest to human ratings is: lechat_hu

Correlation Results:

      AI Model         R p_value
0    lechat_hu  0.969965  < 0.01
2   chatgpt_hu  0.963479  < 0.01
4    gemini_hu  0.960543  < 0.01
1   copilot_hu  0.928583  < 0.01
3  deepseek_hu  0.883830  < 0.01

In [86]:
# Calculate the absolute difference between human mean ratings and each AI model's mean ratings
ai_columns = ['lechat_hu', 'copilot_hu', 'chatgpt_hu', 'deepseek_hu', 'gemini_hu']
diffs = {}

# Calculate the absolute differences
for col in ai_columns:
    diffs[col] = (df_hu['mean_hu'] - df_hu[col]).abs()

# Create a DataFrame to summarize the mean absolute differences for each model
mean_diffs = {col: diffs[col].mean() for col in ai_columns}
mean_diffs_df = pd.DataFrame.from_dict(mean_diffs, orient='index', columns=['mean_absolute_difference'])
mean_diffs_df = mean_diffs_df.sort_values('mean_absolute_difference')

print("Mean absolute difference between human and AI model ratings (lower is closer):")
print(mean_diffs_df)

# Find the AI model with the smallest mean absolute difference
closest_model = mean_diffs_df.index[0]
print(f"\nThe AI model whose mean ratings are closest to human ratings is: {closest_model}")

# Plot (Spearman)
import plotly.figure_factory as ff
from scipy.stats import spearmanr

# Prepare correlation and p-value matrices (Spearman)
corr_cols = ['mean_hu', 'lechat_hu', 'copilot_hu', 'chatgpt_hu', 'deepseek_hu', 'gemini_hu']
df_corr = df_hu_plot[corr_cols].dropna()
corr_matrix = df_corr.corr(method='spearman')

# Compute p-value matrix via spearmanr
pval_matrix = pd.DataFrame(np.ones_like(corr_matrix), columns=corr_matrix.columns, index=corr_matrix.index)
for i in corr_matrix.columns:
    for j in corr_matrix.columns:
        if i == j:
            pval_matrix.loc[i, j] = 0.0
        else:
            rho, p = spearmanr(df_corr[i], df_corr[j])
            pval_matrix.loc[i, j] = p

# Annotate with ρ and p
z_text = [[f"ρ={corr_matrix.iloc[i, j]:.2f}<br>p={pval_matrix.iloc[i, j]:.3g}"
           for j in range(len(corr_matrix))] for i in range(len(corr_matrix))]

fig = ff.create_annotated_heatmap(
    z=corr_matrix.values,
    x=list(corr_matrix.columns),
    y=list(corr_matrix.index),
    annotation_text=z_text,
    colorscale=hungarian_color_scale,
    zmin=-1, zmax=1,
    showscale=True,
    colorbar=dict(title='Spearman ρ')
)

fig.update_layout(
    title='Correlation Matrix (Spearman): Human vs AI Model Ratings',
    font=dict(family="Times New Roman, serif", size=12, color='black'),
    width=600, height=500,
    margin=dict(l=0, r=0, t=40, b=0)
)
fig.show()

# Table
# Prepare a DataFrame with ρ and p for each AI model vs mean_hu
correlation_results = pd.DataFrame({
    'AI Model': ai_columns,
    'rho': [corr_matrix.loc['mean_hu', model] for model in ai_columns],
    'p_value': [pval_matrix.loc['mean_hu', model] for model in ai_columns]
})

# If P value is lower than 0.01, show < 0.01
correlation_results['p_value'] = correlation_results['p_value'].apply(lambda x: '< 0.01' if x < 0.01 else x)

# Sort it by rho
correlation_results = correlation_results.sort_values(by='rho', ascending=False)

print("Correlation Results (Spearman):")
correlation_results

Mean absolute difference between human and AI model ratings (lower is closer):
             mean_absolute_difference
lechat_hu                    0.461665
gemini_hu                    0.639344
deepseek_hu                  0.708690
chatgpt_hu                   0.749542
copilot_hu                   0.753971

The AI model whose mean ratings are closest to human ratings is: lechat_hu

Correlation Results (Spearman):

      AI Model       rho p_value
0    lechat_hu  0.952693  < 0.01
2   chatgpt_hu  0.950243  < 0.01
4    gemini_hu  0.944957  < 0.01
1   copilot_hu  0.897495  < 0.01
3  deepseek_hu  0.882202  < 0.01

In [87]:
df_hu

,hu,en,zh,0,1,2,3,4,5,6,...,chatgpt_zh,chatgpt_zh_std,deepseek_zh,deepseek_zh_std,gemini_zh,gemini_zh_std,mean_hu,std_hu,p_value_hu,significant_hu
27,nővér,nurse (sister),护士 (2),3,3,2,3,3,3,3,...,2.770,0.048305,2.51,0.218327,2.386,0.420190,2.240964,0.835060,2.047581e-39,True
19,kozmetikus,beautician,美容师,2,3,2,3,2,2,2,...,2.875,0.054006,2.35,0.241523,2.569,0.433447,2.120482,0.915951,7.195553e-35,True
15,házvezető,housekeeper,家政员,1,2,0,3,2,2,1,...,2.810,0.056765,2.15,0.241523,2.468,0.437412,1.602410,1.188766,2.847530e-20,True
22,légiutas-kísérő,flight attendant,乘务员,1,2,1,3,0,2,2,...,1.920,0.431535,1.00,0.912871,1.861,0.485671,1.361446,0.994844,1.263333e-20,True
2,HR-es,HR personnel,人事,0,1,0,2,0,1,1,...,1.420,0.113529,1.56,0.157762,1.208,0.375701,1.192771,0.875936,1.652065e-20,True
24,modell,model,模特,2,2,0,2,0,2,2,...,1.730,0.216282,1.45,0.158114,1.001,0.490044,1.084337,0.913380,1.865880e-17,True
38,takarító,cleaner,保洁,1,2,0,3,0,1,-1,...,2.070,0.340098,1.78,0.248551,1.982,0.590476,0.987952,1.338856,2.201366e-09,True
12,fodrász,hairdresser,理发师,0,1,0,0,0,1,1,...,0.290,0.128668,-0.30,0.258199,0.005,0.770501,0.915663,0.843986,1.264903e-15,True
33,pénztáros,cashier,收银员,1,2,0,2,0,2,1,...,2.095,0.111679,1.63,0.216282,1.443,0.416868,0.903614,0.864115,6.456069e-15,True
14,gondozó,caregiver,护工,0,2,0,3,0,2,-1,...,2.430,0.125167,2.07,0.286938,1.610,0.741170,0.795181,1.123573,7.381584e-09,True
9,dietetikus,dietitian,营养师,0,0,0,1,0,1,2,...,2.350,0.212132,0.95,0.598609,1.227,0.327484,0.771084,0.770260,4.150211e-14,True
7,bolti eladó,shop assistant,导购员,1,2,0,2,0,1,1,...,2.060,0.250333,1.68,0.239444,1.354,0.394608,0.759036,0.918514,5.950860e-11,True
21,könyvelő,accountant,会计,1,0,0,2,0,1,-1,...,1.050,0.201384,0.50,0.333333,1.129,0.531966,0.710843,0.862924,6.627569e-11,True
34,recepciós,receptionist,前台,0,1,0,2,0,0,1,...,2.460,0.157762,1.95,0.158114,2.027,0.242581,0.674699,0.797992,2.701484e-11,True
45,ápoló,nurse,护士,1,0,1,3,-3,0,-1,...,2.770,0.048305,2.51,0.218327,2.386,0.420190,0.614458,1.197877,1.148601e-05,True
4,PR munkatárs,PR specialist,公关,0,0,0,1,0,0,1,...,1.630,0.182878,1.37,0.319896,1.154,0.387820,0.554217,0.914024,3.808413e-07,True
16,jegyárus,ticket seller,售票员,0,-1,0,2,0,1,0,...,0.940,0.211870,1.45,0.368932,1.132,0.283972,0.253012,0.809145,5.547307e-03,True
39,tanár,teacher,教师,0,0,0,2,0,0,-1,...,0.370,0.205751,1.45,0.158114,1.018,0.076129,0.108434,1.012267,3.319808e-01,False
10,diák,student,学生,0,0,0,0,0,0,0,...,0.000,0.000000,0.00,0.000000,0.000,0.000000,0.000000,0.312348,1.000000e+00,False
11,felszolgáló,server,服务员 (2),0,-1,0,1,0,0,0,...,0.770,0.221359,0.67,0.365300,1.008,0.250191,-0.048193,0.794856,5.821951e-01,False
40,titkár,secretary,秘书,0,-2,0,0,1,-1,-1,...,1.955,0.151749,2.10,0.316228,2.233,0.360248,-0.048193,1.505305,7.712731e-01,False
8,bíró,judge,法官,-1,0,0,-1,0,0,-1,...,-1.490,0.191195,-0.20,0.258199,-0.688,0.415259,-0.397590,0.936258,2.184064e-04,True
28,orvos,doctor,医生,-1,0,0,-1,0,0,-1,...,-1.020,0.154919,-0.23,0.249666,-0.046,0.430715,-0.469880,0.721404,6.791973e-08,True
30,pincér,waiter,服务员,0,-1,0,1,0,-1,-1,...,0.770,0.221359,0.67,0.365300,1.008,0.250191,-0.590361,1.048066,1.891416e-06,True
47,ügyész,prosecutor,检察官,0,-1,0,-1,0,0,-1,...,-1.675,0.220164,-0.25,0.353553,-0.881,0.370359,-0.650602,0.889419,2.850215e-09,True
41,tudós,scientist,科学家,0,-1,0,-1,0,-1,-1,...,-1.930,0.149443,-0.85,0.241523,-1.254,0.413769,-0.674699,0.856943,2.957730e-10,True
23,menedzser,manager,高管,-1,0,-1,0,0,0,-1,...,-1.645,0.260821,-1.35,0.241523,-1.254,0.589618,-0.746988,0.921867,1.153452e-10,True
35,rendező,director,导演,0,-1,0,-1,0,-1,-1,...,-1.720,0.225093,-1.78,0.248551,-1.857,0.343578,-0.855422,0.813492,5.064698e-15,True
18,kertész,gardener,园丁,0,0,0,-1,-1,-2,-1,...,-0.580,0.131656,-1.25,0.353553,-0.720,0.336782,-0.939759,0.967136,1.414272e-13,True
20,kórboncnok,pathologist,法医,0,-1,0,-1,-2,-1,-1,...,-1.560,0.231900,-1.25,0.263523,-0.973,0.248464,-0.975904,0.999706,1.172215e-13,True
31,professzor,professor,教授,-1,-2,0,-2,0,0,-1,...,-1.580,0.131656,-0.35,0.241523,-0.468,0.528915,-1.000000,0.937043,2.642355e-15,True
37,szakács,chef,厨师,0,0,-1,-1,-1,-2,-1,...,-1.650,0.236878,-1.68,0.239444,-1.912,0.480042,-1.024096,0.826038,2.186931e-18,True
36,rendőr,police officer,警察,-2,-2,-1,-2,-1,-2,-1,...,-2.280,0.153116,-1.55,0.368932,-1.896,0.292848,-1.084337,0.886275,4.239196e-18,True
26,mérnök,engineer,工程师,-2,-1,-1,-2,0,0,-1,...,-2.430,0.094868,-2.12,0.257337,-2.035,0.144318,-1.108434,0.924095,1.127779e-17,True
46,építész,architect,建筑师,-3,-2,-2,-2,0,-1,-1,...,-2.170,0.115950,-1.78,0.248551,-1.965,0.296545,-1.156627,1.005860,8.623230e-17,True
43,vezérigazgató,CEO,董事长,-1,-1,-1,-1,0,-1,-1,...,-1.990,0.191195,-1.70,0.230940,-2.028,0.415473,-1.265060,0.856600,1.857223e-22,True
32,programozó,programmer,程序员,-1,-2,0,-2,-2,-2,-1,...,-2.370,0.125167,-2.10,0.210819,-2.244,0.332104,-1.277108,0.966680,8.279418e-20,True
44,vízimentő,lifeguard,救生员,-1,-2,0,0,0,-2,-1,...,-1.320,0.274064,-1.58,0.293636,-1.389,0.503465,-1.301205,1.020939,5.366343e-19,True
29,pilóta,pilot,飞行员,-1,-2,0,-2,-1,-2,-1,...,-2.530,0.125167,-2.06,0.302581,-2.278,0.368504,-1.530120,0.954289,1.558205e-24,True
13,földműves,farmer,农民,-1,-2,-2,-1,-1,-1,-2,...,-1.490,0.179196,-1.22,0.342540,-0.953,0.459324,-1.626506,1.008632,1.109130e-24,True
25,munkás,worker,工人,0,-2,-2,-1,0,-1,-1,...,-1.900,0.133333,-1.80,0.421637,-1.076,0.281117,-1.638554,1.042725,5.136908e-24,True
17,katona,soldier,军人,-3,-2,-2,-2,-2,-2,-2,...,-2.880,0.042164,-2.42,0.322490,-2.647,0.408848,-1.759036,0.758535,6.396149e-35,True
6,biztonsági őr,security guard,保安,-2,-2,-2,-2,-1,-2,-2,...,-2.735,0.100139,-2.00,0.235702,-2.408,0.452936,-1.771084,0.941267,7.696904e-29,True
42,tűzoltó,firefighter,消防员,-2,-3,0,-2,-2,-3,-2,...,-2.855,0.076194,-2.43,0.340098,-3.000,0.000000,-2.144578,0.898950,8.868375e-36,True
0,Age,NaN,NaN,25-35,45-55,25-35,35-45,25-35,25-35,35-45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Gender,NaN,NaN,male,male,male,male,male,male,female,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mean Rating,NaN,NaN,-0.255814,-0.302326,-0.209302,0.232558,-0.209302,-0.186047,-0.395349,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Participant,NaN,NaN,1,2,3,4,5,6,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Chinese data

In [88]:
# Read Chinese data from hu.xlsx
df_zh = pd.read_excel('ratings_zh.xlsx', engine='openpyxl')

# # Define the mapping for ratings if not already mapped
# rating_map = {
#     1: -3,
#     2: -2,
#     3: -1,
#     4: 0,
#     5: 1,
#     6: 2,
#     7: 3
# }

# # Get columns to convert (skip non-rating columns)
# rating_columns = df_zh.columns[4:]  # assuming first 8 columns are not ratings

# # Replace and explicitly infer objects to avoid warning
# for col in rating_columns:
#     df_zh[col] = df_zh[col].map(rating_map)

# # Rename 您的年龄是？ to Age and 您的性别是？ to Gender
# df_zh.rename(columns={'您的年龄是？': 'Age', '您的性别是？':'Gender', '您的学历是？':'Education'}, inplace=True)

# # Replace 男 to male and 女 to female in Gender column
# df_zh['Gender'] = df_zh['Gender'].replace({'男': 'male', '女': 'female'})

# # In the Age column, change 小于25岁 to <25, 25-35岁 to 25-35, 36-45岁
# df_zh['Age'] = df_zh['Age'].replace({'小于25岁': '<25', '25-35岁': '25-35', '35-45岁': '35-45',})

# Rename ID to Participant
df_zh.rename(columns={'ID': 'Participant'}, inplace=True)

# Count and print participants based on unique Participant
num_participants = df_zh['Participant'].nunique()
print(f'Number of participants: {num_participants}')

# Define Chinese attention checks #######################################
zh_attention_checks = ['妈妈', '女画家', '女作家', '爸爸', '男画家', '男作家'] # '男演员'

# Drop attention checks
df_zh.drop(columns=zh_attention_checks, inplace=True)

########################################################################
# Remove column with missing values (removes 'lawyer' and 'politician')!
df_zh.dropna(axis=1, inplace=True)

# Show
df_zh

Number of participants: 85

,Participant,Age,Gender,Education,警察,秘书,教授,护士,高管,教师,...,农民,学生,园丁,飞行员,人事,消防员,科学家,检察官,救生员,建筑师
0,1,<25,male,master,-1,1,0,1,0,0,...,-1,0,-1,-1,0,-2,0,-1,-2,-1
1,2,<25,female,master,0,1,0,2,0,1,...,0,0,0,0,2,-1,0,0,-1,0
2,3,<25,female,undergraduate,-2,2,-2,2,-2,0,...,-1,-1,-2,-2,2,-2,-2,-2,-2,-2
3,4,<25,female,master,-1,1,-1,2,-1,0,...,0,0,0,-1,0,-2,-1,-1,-1,-2
4,5,<25,male,undergraduate,-1,1,0,2,-1,0,...,-1,0,-1,-1,-1,-2,-1,-1,-2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,81,<25,male,undergraduate,0,2,0,2,0,2,...,0,0,-1,-1,0,-1,-2,-1,-1,-2
81,82,25-35,male,undergraduate,-2,2,-1,2,-1,2,...,-2,0,-1,-2,1,-3,-2,-2,-3,-3
82,83,35-45,male,undergraduate,0,2,0,2,-1,0,...,0,0,0,-2,1,-1,0,-1,-2,0
83,84,<25,male,undergraduate,-1,2,0,2,0,0,...,0,0,-1,-1,1,-1,0,0,-1,-2
84,85,45-55,male,undergraduate,-2,2,0,2,-1,0,...,0,0,0,-1,1,-2,0,-1,-2,-1

### Demographics

In [89]:
color_map = {
    'Men': female_color,
    'Women': male_color,
    'Equal': neutral_color
}

# # Swap colors
# gender_colors = gender_colors[::-1]

# Three shades of teal for age groups
gender_colors = [female_color, male_color]

# Prepare gender and age counts and percentages
gender_counts = df_zh['Gender'].value_counts()
gender_labels = gender_counts.index
gender_labels_en = ['Male' if g == 'male' else 'Female' for g in gender_labels]
gender = gender_counts / gender_counts.sum() * 100

age_counts = df_zh['Age'].value_counts().sort_index()
age = age_counts / age_counts.sum() * 100

# Gender pie with custom colors
gender_pie = go.Pie(
    labels=gender_labels_en,
    values=gender.values,
    name='Gender',
    hole=0.33,
    title='Gender',
    marker=dict(colors=gender_colors),
    customdata=np.stack([gender_labels_en, gender_counts.values, gender.values], axis=-1),
    textinfo='text',
    textfont=dict(size=28),
    text=[f"{label}<br>n={int(n)}<br>{p:.1f}%" for label, n, p in zip(gender_labels_en, gender_counts.values, gender.values)],
)

# Age pie with custom teal shades (repeat if more age groups)
age_pie = go.Pie(
    labels=age.index,
    values=age.values,
    name='Age',
    hole=0.33,
    title='Age',
    marker=dict(colors=age_shades_zh),
    customdata=np.stack([age.index, age_counts.values, age.values], axis=-1),
    textinfo='text',
    textfont=dict(size=28),
    text=[f"{label}<br>n={int(n)}<br>{p:.1f}%" for label, n, p in zip(age.index, age_counts.values, age.values)],
)

# Create subplot with 1 row and 2 columns
fig = make_subplots(
    rows=1, cols=2, specs=[[{'type':'domain'}, {'type':'domain'}]],
    subplot_titles=['Gender Distribution', 'Age Distribution']
)

fig.add_trace(gender_pie, 1, 1)
fig.add_trace(age_pie, 1, 2)

fig.update_layout(
    font = dict(family="Times New Roman, serif", size=32, color='black'),
    margin=dict(l=0, r=0, t=0, b=0),
    showlegend=False,
    legend=dict(
        font=dict(size=28),
        orientation='v',
        x=0.5,
        xanchor='center',
        y=1,
        yanchor='top'
    ),
    annotations=[
        dict(
            text=f'No. of participants: {df_zh.shape[0]}',
            x=0.5, y=0.9, xref='paper', yref='paper',
            showarrow=False, font=dict(size=28), align='center'
        )
    ]
)

# Save it as html
fig.write_html('demographics_zh.html')

# Save it as image
fig.write_image('demographics_zh.png', scale=3, width=1000, height=600)

fig.show()

### Analysis

In [90]:
# Prepare df_zh for clmm
df_zh_clmm = df_zh.copy()

# Drop columns Start time and Completion time and Email and Name and Participant
df_zh_clmm = df_zh_clmm.drop(columns=['Education'])

# Rename Participant to ID
df_zh_clmm.rename(columns={'Participant': 'ID'}, inplace=True)

# Add a prefix to ID values to distinguish Hungarian participants
df_zh_clmm['ID'] = 'zh_' + df_zh_clmm['ID'].astype(str)

# Add a language column with value 'Chinese'
df_zh_clmm['Language'] = 'Chinese'

# Transform from wide to long format, with the items as index
df_zh_clmm = df_zh_clmm.melt(id_vars=['ID', 'Age', 'Gender', 'Language'], var_name='Item', value_name='Rating')

# Add a new column that has the english translations ('en' column) by merging the dataframe with the 'occupations' dataframe's 'zh' column with the df_zh_clmm's 'Item' column and name it 'Occupation'
df_zh_clmm = df_zh_clmm.merge(occupations_for_clmm[['zh', 'en']], left_on='Item', right_on='zh', how='left')

# Rename 'zh' column to 'Occupation'
df_zh_clmm.rename(columns={'en': 'Occupation'}, inplace=True)

# Remove rows where 'Occupation' is 'nurse (sister)'
# df_zh_clmm = df_zh_clmm[df_zh_clmm['Occupation'] != 'nurse (sister)']

# Drop the 'zh' column
df_zh_clmm = df_zh_clmm.drop(columns=['zh'])

# Print number of unique items in df_zh_clmm
print("Number of unique occupations:", num_unique_items := df_zh_clmm['Occupation'].nunique())

# Show 
df_zh_clmm

Number of unique occupations: 41

         ID    Age  Gender Language Item  Rating      Occupation
0      zh_1    <25    male  Chinese   警察      -1  police officer
1      zh_2    <25  female  Chinese   警察       0  police officer
2      zh_3    <25  female  Chinese   警察      -2  police officer
3      zh_4    <25  female  Chinese   警察      -1  police officer
4      zh_5    <25    male  Chinese   警察      -1  police officer
...     ...    ...     ...      ...  ...     ...             ...
3735  zh_81    <25    male  Chinese  建筑师      -2       architect
3736  zh_82  25-35    male  Chinese  建筑师      -3       architect
3737  zh_83  35-45    male  Chinese  建筑师       0       architect
3738  zh_84    <25    male  Chinese  建筑师      -2       architect
3739  zh_85  45-55    male  Chinese  建筑师      -1       architect

[3740 rows x 7 columns]

In [91]:
# Define rating_columns as all columns except 'Participant', 'Age', 'Gender', and 'Occupation'
rating_columns_zh = [col for col in df_zh.columns if col not in ['Participant', 'Age', 'Gender', 'Education']]
rating_columns_zh

['警察',
 '秘书',
 '教授',
 '护士',
 '高管',
 '教师',
 '前台',
 '工人',
 '幼师',
 '模特',
 '护工',
 '保姆',
 '会计',
 '工程师',
 '保洁',
 '法官',
 '导购员',
 '美容师',
 '服务员',
 '乘务员',
 '理发师',
 '空服员',
 '售票员',
 '厨师',
 '营养师',
 '家政员',
 '收银员',
 '医生',
 '法医',
 '程序员',
 '保安',
 '导演',
 '军人',
 '董事长',
 '农民',
 '学生',
 '园丁',
 '飞行员',
 '人事',
 '消防员',
 '科学家',
 '检察官',
 '救生员',
 '建筑师']

#### Two Sample T-Test by Gender

In [92]:
# Add a new column with the mean of the ratings for each participant
df_zh['Mean Rating'] = df_zh.iloc[:, 4:].mean(axis=1)

# Separate df_zh into male and female datasets based on the Gender column
df_zh_male = df_zh[df_zh['Gender'] == 'male']
df_zh_female = df_zh[df_zh['Gender'] == 'female']

# Show the number of male and female participants
print(f"Number of male participants: {df_zh_male['Participant'].nunique()}")
print(f"Number of female participants: {df_zh_female['Participant'].nunique()}")

# Two Sample T-Test between male and female participants for each occupation word
results = []
for col in rating_columns_zh:
    male_ratings = df_zh_male[col].dropna().astype(float)
    female_ratings = df_zh_female[col].dropna().astype(float)
    # Only test if both groups have at least 2 ratings
    if len(male_ratings) > 1 and len(female_ratings) > 1:
        t_stat, p_value = stats.ttest_ind(male_ratings, female_ratings, equal_var=False)
        mean_male = male_ratings.mean()
        mean_female = female_ratings.mean()
        # Get English translation from occupations DataFrame
        en_translation = occupations.loc[occupations['zh'] == col, 'en'].values
        en_translation = en_translation[0] if len(en_translation) > 0 else ""
        results.append({
            'occupation': col,
            'mean_male': mean_male,
            'mean_female': mean_female,
            't_stat': t_stat,
            'p_value': p_value,
            # 'very_highly_significant': p_value is not None and p_value < 0.001,
            # 'highly_significant': p_value is not None and 0.001 <= p_value < 0.01,
            'significant': p_value is not None and p_value < 0.05,
            # 'marg_significant': p_value is not None and 0.05 < p_value < 0.1,
            'en': en_translation
        })

# Create a DataFrame from the results
df_ttest = pd.DataFrame(results)

# Add overall mean rating for sorting
df_ttest['overall_mean'] = (df_ttest['mean_male'] + df_ttest['mean_female']) / 2

# Sort by overall mean rating
df_ttest_sorted = df_ttest.sort_values('overall_mean', ascending=False)

# Prepare axis labels: bold for significant
def bold_label(row):
    occupation = row['occupation']
    # if row.get('very_highly_significant'):
    #     occupation = f"<b>{occupation}***</b>"
    # if row.get('highly_significant'):
    #     occupation = f"<b>{occupation}**</b>"
    if row.get('significant'):
        occupation = f"<b>{occupation}*</b>"
    # if row.get('marg_significant'):
    #     occupation = f"<b>{occupation}+</b>"
    return occupation

df_ttest_sorted['occupation_label'] = df_ttest_sorted.apply(bold_label, axis=1)

# Plot with English translation in hover
fig = go.Figure()

fig.add_trace(go.Bar(
    x=df_ttest_sorted['occupation_label'],
    y=df_ttest_sorted['mean_male'],
    name='Male',
    marker_color=male_color,
    customdata=df_ttest_sorted[['en']],
    hovertemplate='Occupation: %{x}<br>English: %{customdata[0]}<br>Mean (Male): %{y:.2f}<extra></extra>'
))

fig.add_trace(go.Bar(
    x=df_ttest_sorted['occupation_label'],
    y=df_ttest_sorted['mean_female'],
    name='Female',
    marker_color=female_color,
    customdata=df_ttest_sorted[['en']],
    hovertemplate='Occupation: %{x}<br>English: %{customdata[0]}<br>Mean (Female): %{y:.2f}<extra></extra>'
))

fig.update_layout(
    barmode='group',
    xaxis_tickangle=-45,
    yaxis_title='Bias (Male - Female)',
    yaxis=dict(
        range=[-3.1, 3.1],
        tickvals=[-3, -2, -1, 0, 1, 2, 3],
        title='Mean Rating (Bias)'
    ),
    template='plotly_white',
    font=dict(family="Times New Roman, serif", size=16, color='black'),
    margin=dict(l=0, r=0, t=0, b=0),
    legend=dict(
        orientation='h',
        yanchor='bottom',
        y=0,
        xanchor='center',
        x=0.5,
        bgcolor='rgba(220, 220, 220, 0.25)',
    )
)

# Show the plot
fig.show()

# Save it as HTML and image
fig.write_html('occupations_zh_gender.html')
fig.write_image('occupations_zh_gender.png', scale=3, width=1000, height=400)

Number of male participants: 45
Number of female participants: 40

#### Biases and biases by

In [93]:
# Add a column 'bias_by' to df_ttest_sorted: 'Male' if abs(mean_male) > abs(mean_female), 'Female' if abs(mean_female) > abs(mean_male), 'Equal' if they are the same
df_ttest_sorted['bias_by'] = np.where(
    np.abs(df_ttest_sorted['mean_male']) > np.abs(df_ttest_sorted['mean_female']), 'Men',
    np.where(np.abs(df_ttest_sorted['mean_male']) < np.abs(df_ttest_sorted['mean_female']), 'Women', 'Equal')
)

# Add columns that show if the bias is male or female. Add male, if the overall mean is lower than 0, othervise add Female
df_ttest_sorted['bias'] = np.where(
    df_ttest_sorted['overall_mean'] > 0, 'Female',
    np.where(df_ttest_sorted['overall_mean'] < 0, 'Male', 'Equal')
)

# Calculate mean_difference (mean_male - mean_female), and add its absolute value
df_ttest_sorted['mean_difference'] = (df_ttest_sorted['mean_male'] - df_ttest_sorted['mean_female']).abs()

#### Confusion matrix of biases

In [94]:
# Count unique values in 'bias' and 'bias_by' columns, ignoring 'Equal'
# Create confusion matrix, ignoring 'Equal'
conf_matrix_zh = pd.crosstab(
    df_ttest_sorted.loc[df_ttest_sorted['bias'] != 'Equal', 'bias'],
    df_ttest_sorted.loc[df_ttest_sorted['bias_by'] != 'Equal', 'bias_by']
)

# Plot confusion matrix with plotly
fig = go.Figure(data=go.Heatmap(
    z=conf_matrix_zh.values,
    x=conf_matrix_zh.columns,
    y=conf_matrix_zh.index,
    colorscale=chinese_color_scale,
    text=conf_matrix_zh.values,
    texttemplate="%{text}",
    hovertemplate="Bias: %{y}<br>Bias By: %{x}<br>Count: %{z}<extra></extra>"
))

fig.update_layout(
    font=dict(family="Times New Roman, serif", size=28, color='black'),
    margin=dict(l=0, r=0, t=0, b=0),
    title="Confusion Matrix of Biases",
    xaxis_title="Bias By",
    yaxis_title="Bias",
    width=500,
    height=400
)

# Show
fig.show()

# # Save confusion matrix as HTML and image
# fig.write_html('confusion_matrix_zh.html')
# fig.write_image('confusion_matrix_zh.png', scale=3, width=550, height=400)

#### Combined confusion matrices

In [95]:
from plotly.subplots import make_subplots

import plotly.graph_objects as go

# Create subplots
fig = make_subplots(
    rows=1, cols=2,
    subplot_titles=["Hungarian", "Chinese"],
    horizontal_spacing=0.40
)
fig.update_annotations(font_size=32)

# Hungarian confusion matrix heatmap (greenish)
fig.add_trace(
    go.Heatmap(
        z=conf_matrix_hu.values,
        x=conf_matrix_hu.columns,
        y=conf_matrix_hu.index,
        colorscale=hungarian_color_scale,
        text=conf_matrix_hu.values,
        texttemplate="%{text}",
        hovertemplate="Bias: %{y}<br>Bias By: %{x}<br>Count: %{z}<extra></extra>",
        # yaxis =dict(
            # title_text="Bias",
            # side="right",
            # title_standoff=10,
        # )    
    ),
    row=1, col=1
)

# Chinese confusion matrix heatmap (reddish)
fig.add_trace(
    go.Heatmap(
        z=conf_matrix_zh.values,
        x=conf_matrix_zh.columns,
        y=conf_matrix_zh.index,
        colorscale=chinese_color_scale,
        text=conf_matrix_zh.values,
        texttemplate="%{text}",
        hovertemplate="Bias: %{y}<br>Bias By: %{x}<br>Count: %{z}<extra></extra>"
    ),
    row=1, col=2
)

fig.update_traces(showscale=False)

fig.update_layout(
    font=dict(family="Times New Roman, serif", size=32, color='black'),
    margin=dict(l=0, r=0, t=40, b=0),
    width=900,
    height=400,
    # showlegend=False
)

fig.update_xaxes(title_text="Bias By", row=1, col=1)
fig.update_xaxes(title_text="Bias By", row=1, col=2)
fig.update_yaxes(title_text="Bias", row=1, col=1, side="right")
fig.update_yaxes(title_text="Bias", row=1, col=2)

# fig.update_yaxes(
#     showticklabels=True,
#     title_text="Bias",
#     title_standoff=10,
#     side="right",
#     row=1, col=2
# )

fig.show()

# Save the combined confusion matrix as HTML and image
fig.write_html('confusion_matrices.html')
fig.write_image('confusion_matrices.png', scale=3, width=900, height=400)

#### Transpose

In [96]:
# Transpose results, a prepare a copy with only the ratings
df_zh_ratings = df_zh[rating_columns_zh].transpose()
df_zh = df_zh.transpose()

# Remove rows with index: ID, Start Time, Completion time, Email, Name, Participant
df_zh = df_zh.drop(['Participant', 'Education'], axis=0) 

# Print number of rows
print(f"Number of rows: {len(df_zh_ratings)}")

# # Sort by index
# df_zh = df_zh.sort_index()

# Show
df_zh.head()

Number of rows: 44

,0,1,2,3,4,5,6,7,8,9,...,75,76,77,78,79,80,81,82,83,84
Age,<25,<25,<25,<25,<25,<25,<25,<25,35-45,<25,...,25-35,25-35,<25,25-35,<25,<25,25-35,35-45,<25,45-55
Gender,male,female,female,female,male,female,female,male,male,male,...,male,male,male,male,male,male,male,male,male,male
警察,-1,0,-2,-1,-1,-1,0,-2,-1,-2,...,-1,-1,0,-1,-1,0,-2,0,-1,-2
秘书,1,1,2,1,1,0,0,2,1,0,...,1,3,1,1,2,2,2,2,2,2
教授,0,0,-2,-1,0,-1,-1,-2,0,-1,...,0,0,0,1,-1,0,-1,0,0,0

#### One Sample T-test

In [97]:
# One Sample T-test with standard deviation
results = []

for index, row in df_zh_ratings.iterrows():
    ratings = row.dropna().astype(float)
    t_stat, p_value = stats.ttest_1samp(ratings, popmean=0)
    mean_rating = ratings.mean()
    std_rating = ratings.std()
    results.append({
        'item': index,  # item name from index
        'mean': mean_rating,
        'std': std_rating,
        't_stat': t_stat,
        'p_value': p_value,
        'significant': p_value < 0.05
    })

df_results = pd.DataFrame(results)

# Print significant results
print(df_results[df_results['significant']][['item', 'mean', 'std', 'p_value']])

# Filter for non-significant ratings
not_significant = df_results[~df_results['significant']]

# Get the min and max of the mean ratings where not significant
mean_min = not_significant['mean'].min()
mean_max = not_significant['mean'].max()

# Print the range of mean ratings where the rating is not significant
print(f"\nRange of mean ratings where the rating is not significant: {mean_min} to {mean_max}")

   item      mean       std       p_value
0    警察 -1.035294  0.625777  6.293553e-26
1    秘书  1.447059  0.732021  6.267380e-31
2    教授 -0.341176  0.664633  8.873634e-06
3    护士  1.788235  0.599486  8.988993e-44
4    高管 -0.517647  0.780899  2.976162e-08
5    教师  0.729412  0.822138  2.647659e-12
6    前台  1.635294  0.799510  6.231995e-32
7    工人 -1.188235  0.932152  2.003862e-19
8    幼师  1.788235  0.656363  8.047857e-41
9    模特  0.752941  0.829599  1.110862e-12
10   护工  1.141176  1.025310  1.744481e-16
11   保姆  1.800000  0.720450  4.664974e-38
12   会计  0.635294  0.784478  7.020305e-11
13  工程师 -0.976471  0.844823  2.857106e-17
14   保洁  1.223529  0.850441  2.606639e-22
15   法官 -0.388235  0.757410  9.114634e-06
16  导购员  1.023529  0.801434  1.815009e-19
17  美容师  1.670588  0.836493  3.145050e-31
18  服务员  0.588235  0.791233  1.121196e-09
19  乘务员  0.847059  0.866106  5.489350e-14
20  理发师 -0.635294  0.799510  1.330864e-10
21  空服员  0.882353  1.016668  6.023353e-12
22  售票员  0.800000  0.813575  4.375557e-14
23   厨师 -1.047059  0.857820  1.891302e-18
24  营养师  0.435294  0.822989  5.053783e-06
25  家政员  1.011765  0.879585  3.610556e-17
26  收银员  1.129412  0.827910  5.177375e-21
27   医生 -0.164706  0.651867  2.223402e-02
28   法医 -0.623529  0.886089  5.732612e-09
29  程序员 -1.270588  0.746232  1.045446e-26
30   保安 -1.752941  0.785370  1.478894e-34
31   导演 -0.682353  0.848132  8.770879e-11
32   军人 -1.082353  0.727222  3.672058e-23
33  董事长 -0.882353  0.822478  9.617076e-16
34   农民 -0.458824  0.780002  5.524401e-07
36   园丁 -0.470588  0.867237  3.059363e-06
37  飞行员 -1.247059  0.688440  2.006563e-28
38   人事  0.658824  0.866753  5.619637e-10
39  消防员 -1.788235  0.887668  1.749456e-31
40  科学家 -0.564706  0.731063  3.362252e-10
41  检察官 -0.458824  0.780002  5.524401e-07
42  救生员 -1.576471  0.777304  1.108600e-31
43  建筑师 -1.117647  0.891918  4.903342e-19

Range of mean ratings where the rating is not significant: -0.03529411764705882 to -0.03529411764705882

In [98]:
# Sort by mean for better readability
df_results_sorted = df_results.sort_values(by='mean')

# Create color labels
df_results_sorted['Significance'] = df_results_sorted['significant'].map({True: 'significant', False: 'not significant'})

# Plot
fig = px.bar(
    df_results_sorted,
    x='item',
    y='mean',
    color='Significance',
    color_discrete_map={'significant': 'crimson', 'not significant': 'lightgray'},
    title='One Sample T-test of Raw Ratings',
    labels={'item': 'Item', 'mean': 'Mean Rating'},
    # On hover, Show the item, mean rating, and p-value    
    hover_data=['item', 'mean', 'p_value'],
    # Edit hovertemplate to show item, mean, and p-value
    
)

fig.update_layout(
    xaxis_tickangle=-45,
    template='plotly_white',
    margin=dict(l=0, r=0, t=40, b=0),
    legend=dict(
        orientation='h',
        yanchor='bottom',
        y=0,
        xanchor='center',
        x=0.5,
        bgcolor='rgba(220, 220, 220, 0.25)',
    )
)

# Show
fig.show()

# # Save it as html
# fig.write_html('occupations_ttest_zh.html')
# fig.write_image('occupations_ttest_zh.png', scale=3, width=1000, height=400)

#### Merge

In [99]:
# Turn index column into a column called 'zh'
df_zh.reset_index(inplace=True)
df_zh.rename(columns={'index': 'zh'}, inplace=True)

# Merge df_zh and occupations on the 'zh' column
df_zh = pd.merge(df_zh, occupations, on='zh', how='left')

# Reorder columns so the dataframe starts with 'zh' 'en', 'zh', and so on
df_zh = df_zh[['zh', 'en', 'hu'] + [col for col in df_zh.columns if col not in ['zh', 'en' , 'hu']]]

# Merge df_zh and df_results on the 'hu' column
df_zh = pd.merge(df_zh, df_results, left_on='zh', right_on='item', how='left')

# Sort all occupations by their average ratings
df_zh = df_zh.sort_values(by='mean', ascending=False)

# Drop redundant columns
df_zh.drop(columns=['item', 't_stat'], inplace=True)

# Rename the columns for clarity
df_zh.rename(columns={'mean': 'mean_zh',
                      't_stat': 't_stat_zh',
                      'std': 'std_zh',
                      'p_value': 'p_value_zh',
                      'significant': 'significant_zh'}, inplace=True)

# Save df_zh as an Excel file
# df_zh.to_excel('occupations_zh.xlsx', index=False)

# Show the final DataFrame
df_zh.head()

#Show
df_zh.tail()

,zh,en,hu,0,1,2,3,4,5,6,...,chatgpt_zh,chatgpt_zh_std,deepseek_zh,deepseek_zh_std,gemini_zh,gemini_zh_std,mean_zh,std_zh,p_value_zh,significant_zh
32,保安,security guard,biztonsági őr,-2,-1,-2,-1,-2,-2,-1,...,-2.735,0.100139,-2.00,0.235702,-2.408,0.452936,-1.752941,0.785370,1.478894e-34,True
41,消防员,firefighter,tűzoltó,-2,-1,-2,-2,-2,-2,-2,...,-2.855,0.076194,-2.43,0.340098,-3.000,0.000000,-1.788235,0.887668,1.749456e-31,True
0,Age,NaN,NaN,<25,<25,<25,<25,<25,<25,<25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Gender,NaN,NaN,male,female,female,female,male,female,female,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Mean Rating,NaN,NaN,-0.204545,0.204545,-0.363636,-0.204545,-0.272727,-0.25,0.204545,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [100]:
# Show only rating rows for student
df_zh[df_zh['en'] == 'student'].iloc[:, 4:-12]

,1,2,3,4,5,6,7,8,9,10,...,copilot_hu,copilot_hu_std,chatgpt_hu,chatgpt_hu_std,deepseek_hu,deepseek_hu_std,gemini_hu,gemini_hu_std,lechat_zh,lechat_zh_std
37,0,-1,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.001,0.003162,0.0,0.0

In [101]:
# Get the top 5 words with the smallest standard deviation from df_hu
top_smallest_std = df_zh.nsmallest(5, 'std_zh')[['zh', 'en', 'std_zh']]
print(top_smallest_std)

    zh                    en    std_zh
37  学生               student  0.286484
5   护士                 nurse  0.599486
2   警察        police officer  0.625777
29  医生                doctor  0.651867
10  幼师  kindergarten teacher  0.656363

In [102]:
# # Find duplicate values in the 'zh' column
# duplicates = df_zh['zh'][df_zh['zh'].duplicated(keep=False)]

# # Show duplicate rows
# duplicate_rows = df_zh[df_zh['zh'].isin(duplicates)]
# print("Duplicate rows in 'zh' column:")
# print(duplicate_rows[['zh', 'en', 'hu']])

# # # If there are duplicates, append (2) to the second and further occurrences
# # if not duplicates.empty:
# #     # Create a counter for each zh value
# #     zh_counts = {}
# #     def append_suffix(zh):
# #         count = zh_counts.get(zh, 0) + 1
# #         zh_counts[zh] = count
# #         if count > 1:
# #             return f"{zh}(2)"
# #         return zh
# #     df_zh['zh'] = df_zh['zh'].apply(append_suffix)

# # df_zh

# # If there are duplicates, remove the second one
# if not duplicates.empty:
#     # Create a mask for duplicates
#     mask = df_zh.duplicated(subset=['zh'], keep='first')
#     # Keep only the first occurrence of each duplicate
#     df_zh = df_zh[~mask]
# # Show the DataFrame after removing duplicates
# print("DataFrame after removing duplicates:")
# print(df_zh[['zh', 'en', 'hu']])

In [103]:
# Get the top 5 words with the smallest standard deviation from df_hu
top_smallest_std = df_zh.nsmallest(5, 'std_zh')[['zh', 'en', 'std_zh']]
print(top_smallest_std)

    zh                    en    std_zh
37  学生               student  0.286484
5   护士                 nurse  0.599486
2   警察        police officer  0.625777
29  医生                doctor  0.651867
10  幼师  kindergarten teacher  0.656363

#### Plot

In [104]:
# Make an explicit copy of the filtered DataFrame
df_zh_plot = df_zh[~df_zh['zh'].isin(['Age', 'Gender', 'Mean Rating'])].copy()

# Assign the 'bias' column safely
df_zh_plot.loc[:, 'bias'] = df_zh_plot['mean_zh'].apply(
    lambda x: 'Female' if x > mean_max else ('Male' if x < mean_min else 'Neutral')
)

color_map = {
    'Female': female_color, # '#e377c2',   # pinkish
    'Male': male_color, # '#1f77b4',  # blue
    'Neutral': neutral_color     # gray
}

# Sort df_zh_plot by mean value before plotting
df_zh_plot_sorted = df_zh_plot.sort_values('mean_zh', ascending=False)

df_zh_plot_sorted['label_zh'] = df_zh_plot_sorted.apply(
    lambda row: f"{row['zh']} ({row['en']})" if pd.notna(row['en']) else row['zh'], axis=1
)

fig = go.Figure()

for bias in ['Female', 'Neutral', 'Male']:
    subset = df_zh_plot_sorted[df_zh_plot_sorted['bias'] == bias]
    fig.add_trace(go.Bar(
        x=subset['zh'],
        y=subset['mean_zh'],
        error_y=dict(type='data', array=subset['std_zh'], thickness=0.75),
        name=bias,
        marker_color=color_map[bias],
        hovertemplate=(
            'Chinese: %{x}<br>'
            'Mean Rating: %{y:.2f}<br>'
            'Standard Deviation: %{error_y.array:.2f}<br>'
            'English: %{customdata[0]}<br>'
            'Hungarian: %{customdata[1]}<extra></extra>'
        ),
        customdata=subset[['en', 'hu']]
    ))

fig.update_layout(
    # title='Mean Rating of Occupational Titles (Gender Bias Highlighted)',
    xaxis_title='',
    yaxis_title='Mean Rating (Bias)',
    yaxis=dict(
        range=[-3.05, 3.05],
        tickvals=[-3, -2, -1, 0, 1, 2, 3],
        title='Mean Rating (Bias)'
    ),
    xaxis_tickangle=-45,
    template='plotly_white',
    font = dict(family="Times New Roman, serif", size=16, color='black'),
    margin=dict(l=0, r=0, t=0, b=0),
    legend=dict(
        orientation='h',
        yanchor='bottom',
        y=0,
        xanchor='center',
        x=0.5,
        bgcolor='rgba(220, 220, 220, 0.25)',
    )
)

fig.show()

# Save this as a html and image
fig.write_html('occupations_zh.html')
fig.write_image('occupations_zh.png', scale=3, width=1000, height=400)

In [105]:
# Plot the Chinese data with LLM reference lines using plotly.graph_objects (go)
fig = go.Figure()

# Add bars for each bias category
for bias in ['Female', 'Neutral', 'Male']:
    subset = df_zh_plot_sorted[df_zh_plot_sorted['bias'] == bias]
    fig.add_trace(go.Bar(
        x=subset['zh'],
        y=subset['mean_zh'],
        error_y=dict(type='data', array=subset['std_zh'], thickness=0.75, visible=False),
        name=bias,
        marker_color=color_map[bias],
        hovertemplate=(
            'Chinese: %{x}<br>'
            'Mean Rating: %{y:.2f}<br>'
            # 'STD: %{error_y.array:.2f}<br>'
            'English: %{customdata[0]}<br>'
            'Hungarian: %{customdata[1]}<extra></extra>'
        ),
        customdata=subset[['en', 'hu']]
    ))

# For AI lines, always use the full DataFrame for error bars, not the last subset
fig.add_trace(go.Scatter(
    x=df_zh_plot_sorted['zh'],
    y=df_zh_plot_sorted['lechat_zh'],
    error_y=dict(type='data', array=df_zh_plot_sorted['lechat_zh_std'], thickness=1),
    mode='lines+markers',
    name='Le Chat',
    line=dict(color="#f95010", width=2, dash='dot'),
    marker=dict(symbol='star-square', size=8),
    hovertemplate=(
        'Chinese: %{x}<br>'
        'English: %{customdata[0]}<br>'
        'Le Chat: %{y:.2f}<br>'
        'STD: %{customdata[1]:.2f}<extra></extra>'
    ),
    customdata=df_zh_plot_sorted[['en', 'lechat_zh_std']]
))

fig.add_trace(go.Scatter(
    x=df_zh_plot_sorted['zh'],
    y=df_zh_plot_sorted['copilot_zh'],
    error_y=dict(type='data', array=df_zh_plot_sorted['copilot_zh_std'], thickness=1),
    mode='lines+markers',
    name='Copilot',
    line=dict(color="#F2AD22", width=2, dash='dot'),
    marker=dict(symbol='pentagon', size=8),
    hovertemplate=(
        'Chinese: %{x}<br>'
        'English: %{customdata[0]}<br>'
        'Copilot: %{y:.2f}<br>'
        'STD: %{customdata[1]:.2f}<extra></extra>'
    ),
    customdata=df_zh_plot_sorted[['en', 'copilot_zh_std']]
))

fig.add_trace(go.Scatter(
    x=df_zh_plot_sorted['zh'],
    y=df_zh_plot_sorted['chatgpt_zh'],
    error_y=dict(type='data', array=df_zh_plot_sorted['chatgpt_zh_std'], thickness=1),
    mode='lines+markers',
    name='ChatGPT',
    line=dict(color='#00A67E', width=2, dash='dot'),
    marker=dict(symbol='hexagon', size=8),
    hovertemplate=(
        'Chinese: %{x}<br>'
        'English: %{customdata[0]}<br>'
        'ChatGPT: %{y:.2f}<br>'
        'STD: %{customdata[1]:.2f}<extra></extra>'
    ),
    customdata=df_zh_plot_sorted[['en', 'chatgpt_zh_std']]
))

fig.add_trace(go.Scatter(
    x=df_zh_plot_sorted['zh'],
    y=df_zh_plot_sorted['deepseek_zh'],
    error_y=dict(type='data', array=df_zh_plot_sorted['deepseek_zh_std'], thickness=1),
    mode='lines+markers',
    name='Deepseek',
    line=dict(color='#3C5DFF', width=2, dash='dot'),
    marker=dict(symbol='circle', size=8),
    hovertemplate=(
        'Chinese: %{x}<br>'
        'English: %{customdata[0]}<br>'
        'Deepseek: %{y:.2f}<br>'
        'STD: %{customdata[1]:.2f}<extra></extra>'
    ),
    customdata=df_zh_plot_sorted[['en', 'deepseek_zh_std']]
))

fig.add_trace(go.Scatter(
    x=df_zh_plot_sorted['zh'],
    y=df_zh_plot_sorted['gemini_zh'],
    error_y=dict(type='data', array=df_zh_plot_sorted['gemini_zh_std'], thickness=1),
    mode='lines+markers',
    name='Gemini',
    line=dict(color='#9177C7', width=2, dash='dot'),
    marker=dict(symbol='star-diamond', size=8),
    hovertemplate=(
        'Chinese: %{x}<br>'
        'English: %{customdata[0]}<br>'
        'Gemini: %{y:.2f}<br>'
        'STD: %{customdata[1]:.2f}<extra></extra>'
    ),
    customdata=df_zh_plot_sorted[['en', 'gemini_zh_std']]
))

fig.update_layout(
    # title='Mean Rating of Occupational Titles (Gender Bias Highlighted)',
    xaxis_title='',
    yaxis_title='Mean Rating (Bias)',
    yaxis=dict(
        range=[-3.1, 3.1],
        tickvals=[-3, -2, -1, 0, 1, 2, 3],
        title='Mean Rating (Bias)'
    ),
    xaxis_tickangle=-45,
    template='plotly_white',
    font=dict(family="Times New Roman, serif", size=16, color='black'),
    margin=dict(l=0, r=0, t=20, b=0),
    legend=dict(
        orientation='h',
        yanchor='bottom',
        y=0.95,
        xanchor='center',
        x=0.5,
        bgcolor='rgba(220, 220, 220, 0.25)',
    )
)

fig.show()

# Save as HTML and image
fig.write_html('occupations_zh_with_ai.html')
fig.write_image('occupations_zh_with_ai.png', scale=3, width=1000, height=400)

#### AI agreement and variation

In [106]:
# Select only the relevant AI mean rating columns
ai_mean_cols = ['lechat_zh', 'copilot_zh', 'chatgpt_zh', 'deepseek_zh', 'gemini_zh']

# Calculate the standard deviation and range across AI models for each word
df_zh_plot_sorted['ai_std'] = df_zh_plot_sorted[ai_mean_cols].std(axis=1)
df_zh_plot_sorted['ai_range'] = df_zh_plot_sorted[ai_mean_cols].max(axis=1) - df_zh_plot_sorted[ai_mean_cols].min(axis=1)

# # Top 5 words with highest agreement (lowest std)
# top_agreement = df_zh_plot_sorted.nsmallest(10, 'ai_std')[['zh', 'en', 'ai_std', 'ai_range'] + ai_mean_cols]
# print("Top 5 words with highest agreement between AI models:")
# print(top_agreement)

# # Top 5 words with highest variation (highest std)
# top_variation = df_zh_plot_sorted.nlargest(10, 'ai_std')[['zh', 'en', 'ai_std', 'ai_range'] + ai_mean_cols]
# print("\nTop 5 words with highest variation between AI models:")
# print(top_variation)

In [107]:
import plotly.graph_objects as go

# Sort the full DataFrame by ai_std (lowest to highest)
df_ai_sorted = df_zh_plot_sorted.sort_values('ai_std')

# Prepare data for plotting
x_labels = df_ai_sorted['en']
zh_labels = df_ai_sorted['zh']
means = df_ai_sorted[['lechat_zh', 'copilot_zh', 'chatgpt_zh', 'deepseek_zh', 'gemini_zh']].values.T
models = ['Le Chat', 'Copilot', 'ChatGPT', 'Deepseek', 'Gemini']
colors = ['#f95010', '#F2AD22', '#00A67E', '#3C5DFF', '#9177C7']
markers = ['star-square', 'pentagon', 'hexagon', 'circle', 'star-diamond']

fig = go.Figure()

# Plot each model's mean as a scatter with markers (not lines)
for i, (model, color, marker) in enumerate(zip(models, colors, markers)):
    fig.add_trace(go.Scatter(
        x=x_labels,
        y=means[i],
        mode='markers',
        name=model,
        marker=dict(size=14, color=color, symbol=marker),
        customdata=np.stack([zh_labels], axis=-1),
        hovertemplate=f"{model}: %{{y:.2f}}<br>Occupation: %{{x}}<br>Chinese: %{{customdata[0]}}"
    ))

# Add error bars for std
fig.add_trace(go.Bar(
    x=x_labels,
    y=df_ai_sorted['ai_std'],
    name='STD (AI models)',
    marker_color='gray',
    opacity=0.5,
    yaxis='y2',
    customdata=np.stack([zh_labels], axis=-1),
    hovertemplate='STD: %{y:.3f}<br>Occupation: %{x}<br>Chinese: %{customdata[0]}'
))

# Add bar for range
fig.add_trace(go.Bar(
    x=x_labels,
    y=df_ai_sorted['ai_range'],
    name='Range (AI models)',
    marker_color='lightgray',
    opacity=0.5,
    yaxis='y2',
    customdata=np.stack([zh_labels], axis=-1),
    hovertemplate='Range: %{y:.3f}<br>Occupation: %{x}<br>Chinese: %{customdata[0]}'
))

# Set up secondary y-axis for std and range
fig.update_layout(
    title='AI agent agreement and variation across Chinese occupations',
    yaxis=dict(
        title='Mean Rating (Bias)',
        range=[-3.2, 3.2],
        tickvals=[-3, -2, -1, 0, 1, 2, 3]
    ),
    yaxis2=dict(
        title='STD / Range',
        overlaying='y',
        side='right',
        showgrid=False
    ),
    barmode='group',
    legend=dict(
        orientation='h',
        yanchor='bottom',
        y=1.025,
        xanchor='center',
        x=0.7
    ),
    template='plotly_white',
    margin=dict(l=0, r=0, t=0, b=0),
    font=dict(family="Times New Roman, serif", size=16, color='black'),
    xaxis_tickangle=45  # Rotate x-axis tick labels by 45 degrees
)

fig.show()

#### Correlation

In [108]:
# Calculate the absolute difference between human mean ratings and each AI model's mean ratings
ai_columns = ['lechat_zh', 'copilot_zh', 'chatgpt_zh', 'deepseek_zh', 'gemini_zh']
diffs = {}

# Calculate the absolute differences
for col in ai_columns:
    diffs[col] = (df_zh['mean_zh'].abs() - df_zh[col]).abs()

# Create a DataFrame to summarize the mean absolute differences for each model
mean_diffs = {col: diffs[col].mean() for col in ai_columns}
mean_diffs_df = pd.DataFrame.from_dict(mean_diffs, orient='index', columns=['mean_absolute_difference'])
mean_diffs_df = mean_diffs_df.sort_values('mean_absolute_difference')

print("Mean absolute difference between human and AI model ratings (lower is closer):")
print(mean_diffs_df)

# Find the AI model with the smallest mean absolute difference
closest_model = mean_diffs_df.index[0]
print(f"\nThe AI model whose mean ratings are closest to human ratings is: {closest_model}")



# Plot
import plotly.figure_factory as ff
from scipy.stats import pearsonr

# Prepare correlation and p-value matrices as before
corr_cols = ['mean_zh', 'lechat_zh', 'copilot_zh', 'chatgpt_zh', 'deepseek_zh', 'gemini_zh']
df_corr = df_zh_plot[corr_cols].dropna()
corr_matrix = df_corr.corr(method='pearson')

# Compute p-value matrix
pval_matrix = pd.DataFrame(np.ones_like(corr_matrix), columns=corr_matrix.columns, index=corr_matrix.index)
for i in corr_matrix.columns:
    for j in corr_matrix.columns:
        if i == j:
            pval_matrix.loc[i, j] = 0.0
        else:
            r, p = pearsonr(df_corr[i], df_corr[j])
            pval_matrix.loc[i, j] = p

# Annotate with R and p
z_text = [[f"R={corr_matrix.iloc[i, j]:.2f}<br>p={pval_matrix.iloc[i, j]:.3g}" 
           for j in range(len(corr_matrix))] for i in range(len(corr_matrix))]

fig = ff.create_annotated_heatmap(
    z=corr_matrix.values,
    x=list(corr_matrix.columns),
    y=list(corr_matrix.index),
    annotation_text=z_text,
    colorscale=chinese_color_scale,
    zmin=-1, zmax=1,
    showscale=True,
    colorbar=dict(title='Pearson R')
)

fig.update_layout(
    title='Correlation Matrix: Human vs AI Model Ratings',
    font=dict(family="Times New Roman, serif", size=12, color='black'),
    width=600, height=500,
    margin=dict(l=0, r=0, t=40, b=0)
)
fig.show()



# Table
# Prepare a DataFrame with R and p for each AI model vs mean_zh
correlation_results = pd.DataFrame({
    'AI Model': ai_columns,
    'R': [corr_matrix.loc['mean_zh', model] for model in ai_columns],
    'p_value': [pval_matrix.loc['mean_zh', model] for model in ai_columns]
})

# If P value is lower than 0.01, show < 0.01
correlation_results['p_value'] = correlation_results['p_value'].apply(lambda x: '< 0.01' if x < 0.01 else x)

# Sort it by R
correlation_results = correlation_results.sort_values(by='R', ascending=False)

print("Correlation Results:")
correlation_results

Mean absolute difference between human and AI model ratings (lower is closer):
             mean_absolute_difference
deepseek_zh                  1.487233
lechat_zh                    1.530194
gemini_zh                    1.531833
copilot_zh                   1.657660
chatgpt_zh                   1.827533

The AI model whose mean ratings are closest to human ratings is: deepseek_zh

Correlation Results:

      AI Model         R p_value
3  deepseek_zh  0.971072  < 0.01
4    gemini_zh  0.968229  < 0.01
2   chatgpt_zh  0.948528  < 0.01
0    lechat_zh  0.948309  < 0.01
1   copilot_zh  0.942486  < 0.01

In [109]:
# Calculate the absolute difference between human mean ratings and each AI model's mean ratings
ai_columns = ['lechat_zh', 'copilot_zh', 'chatgpt_zh', 'deepseek_zh', 'gemini_zh']
diffs = {}

# Calculate the absolute differences
for col in ai_columns:
    diffs[col] = (df_zh['mean_zh'].abs() - df_zh[col]).abs()

# Create a DataFrame to summarize the mean absolute differences for each model
mean_diffs = {col: diffs[col].mean() for col in ai_columns}
mean_diffs_df = pd.DataFrame.from_dict(mean_diffs, orient='index', columns=['mean_absolute_difference'])
mean_diffs_df = mean_diffs_df.sort_values('mean_absolute_difference')

print("Mean absolute difference between human and AI model ratings (lower is closer):")
print(mean_diffs_df)

# Find the AI model with the smallest mean absolute difference
closest_model = mean_diffs_df.index[0]
print(f"\nThe AI model whose mean ratings are closest to human ratings is: {closest_model}")

# Plot (Spearman)
import plotly.figure_factory as ff
from scipy.stats import spearmanr

# Prepare correlation and p-value matrices (Spearman)
corr_cols = ['mean_zh', 'lechat_zh', 'copilot_zh', 'chatgpt_zh', 'deepseek_zh', 'gemini_zh']
df_corr = df_zh_plot[corr_cols].dropna()
corr_matrix = df_corr.corr(method='spearman')

# Compute p-value matrix via spearmanr
pval_matrix = pd.DataFrame(np.ones_like(corr_matrix), columns=corr_matrix.columns, index=corr_matrix.index)
for i in corr_matrix.columns:
    for j in corr_matrix.columns:
        if i == j:
            pval_matrix.loc[i, j] = 0.0
        else:
            rho, p = spearmanr(df_corr[i], df_corr[j])
            pval_matrix.loc[i, j] = p

# Annotate with ρ and p
z_text = [[f"ρ={corr_matrix.iloc[i, j]:.2f}<br>p={pval_matrix.iloc[i, j]:.3g}"
           for j in range(len(corr_matrix))] for i in range(len(corr_matrix))]

fig = ff.create_annotated_heatmap(
    z=corr_matrix.values,
    x=list(corr_matrix.columns),
    y=list(corr_matrix.index),
    annotation_text=z_text,
    colorscale=chinese_color_scale,
    zmin=-1, zmax=1,
    showscale=True,
    colorbar=dict(title='Spearman ρ')
)

fig.update_layout(
    title='Correlation Matrix (Spearman): Human vs AI Model Ratings',
    font=dict(family="Times New Roman, serif", size=12, color='black'),
    width=600, height=500,
    margin=dict(l=0, r=0, t=40, b=0)
)
fig.show()

# Table
# Prepare a DataFrame with ρ and p for each AI model vs mean_zh
correlation_results = pd.DataFrame({
    'AI Model': ai_columns,
    'rho': [corr_matrix.loc['mean_zh', model] for model in ai_columns],
    'p_value': [pval_matrix.loc['mean_zh', model] for model in ai_columns]
})

# If P value is lower than 0.01, show < 0.01
correlation_results['p_value'] = correlation_results['p_value'].apply(lambda x: '< 0.01' if x < 0.01 else x)

# Sort it by rho
correlation_results = correlation_results.sort_values(by='rho', ascending=False)

print("Correlation Results (Spearman):")
correlation_results

Mean absolute difference between human and AI model ratings (lower is closer):
             mean_absolute_difference
deepseek_zh                  1.487233
lechat_zh                    1.530194
gemini_zh                    1.531833
copilot_zh                   1.657660
chatgpt_zh                   1.827533

The AI model whose mean ratings are closest to human ratings is: deepseek_zh

Correlation Results (Spearman):

      AI Model       rho p_value
3  deepseek_zh  0.968561  < 0.01
4    gemini_zh  0.959862  < 0.01
0    lechat_zh  0.944866  < 0.01
1   copilot_zh  0.929030  < 0.01
2   chatgpt_zh  0.928536  < 0.01

## Cross-linguistic Comparison

### Check comparability

In [110]:
# Get the set of English occupation names from both dataframes
en_hu = set(df_hu['en'].dropna()) if 'en' in df_hu.columns else set()
en_zh = set(df_zh['en'].dropna()) if 'en' in df_zh.columns else set()

# Items only in Hungarian data
only_in_hu = en_hu - en_zh
# Items only in Chinese data
only_in_zh = en_zh - en_hu
# Items in both
in_both = en_hu & en_zh

print(f"Items only in Hungarian data ({len(only_in_hu)}): {sorted(only_in_hu)}\n")
print(f"Items only in Chinese data ({len(only_in_zh)}): {sorted(only_in_zh)}\n")
print(f"Items in both ({len(in_both)}): {sorted(in_both)}")

Items only in Hungarian data (3): ['PR specialist', 'nurse (sister)', 'server']

Items only in Chinese data (3): ['flight attendant (2)', 'kindergarten teacher', 'nanny']

Items in both (41): ['CEO', 'HR personnel', 'accountant', 'architect', 'beautician', 'caregiver', 'cashier', 'chef', 'cleaner', 'dietitian', 'director', 'doctor', 'engineer', 'farmer', 'firefighter', 'flight attendant', 'gardener', 'hairdresser', 'housekeeper', 'judge', 'lifeguard', 'manager', 'model', 'nurse', 'pathologist', 'pilot', 'police officer', 'professor', 'programmer', 'prosecutor', 'receptionist', 'scientist', 'secretary', 'security guard', 'shop assistant', 'soldier', 'student', 'teacher', 'ticket seller', 'waiter', 'worker']

### Unified dataframe

In [111]:
# Create a unified DataFrame with all unique occupation words (by English name)
all_en = sorted(en_hu | en_zh)

# Merge Hungarian and Chinese data on 'en' (English occupation name)
df_hu_part = df_hu[['en', 'hu', 'mean_hu', 'significant_hu']].copy()
df_zh_part = df_zh[['en', 'zh', 'mean_zh', 'significant_zh']].copy()

# Outer merge to include all occupations from both datasets
df_unified = pd.DataFrame({'en': all_en})
df_unified = df_unified.merge(df_hu_part, on='en', how='left')
df_unified = df_unified.merge(df_zh_part, on='en', how='left')

# Mark in a new column if both are significant
df_unified['both_significant'] = df_unified.apply(
    lambda row: row['significant_hu'] and row['significant_zh'] if pd.notna(row['significant_hu']) and pd.notna(row['significant_zh']) else False, axis=1)

# Drop significant_hu and significant_zh columns
df_unified.drop(columns=['significant_hu', 'significant_zh'], inplace=True)

# Add new column that shows the difference between mean_hu and mean_zh
df_unified['mean_difference'] = df_unified.apply(
    lambda row: row['mean_hu'] - row['mean_zh'] if pd.notna(row['mean_hu']) and pd.notna(row['mean_zh']) else None, axis=1)

# Sort by this
df_unified = df_unified.sort_values(by='mean_difference', ascending=False)

# Reset index
df_unified.reset_index(drop=True, inplace=True)

# Get rid of rows that have NA values
df_unified.dropna(inplace=True)

# Count and print the number of unique occupations in the unified DataFrame
print(f'Number of occupations in unified DataFrame: {len(df_unified)}')

# Export this as an Excel file
# df_unified.to_excel('occupations_unified.xlsx', index=False)

# Show the unified DataFrame
df_unified

Number of occupations in unified DataFrame: 41

,en,hu,mean_hu,zh,mean_zh,both_significant,mean_difference
0,hairdresser,fodrász,0.915663,理发师,-0.635294,True,1.550957
1,housekeeper,házvezető,1.602410,家政员,1.011765,True,0.590645
2,HR personnel,HR-es,1.192771,人事,0.658824,True,0.533948
3,flight attendant,légiutas-kísérő,1.361446,乘务员,0.847059,True,0.514387
4,beautician,kozmetikus,2.120482,美容师,1.670588,True,0.449894
5,dietitian,dietetikus,0.771084,营养师,0.435294,True,0.335790
6,model,modell,1.084337,模特,0.752941,True,0.331396
7,lifeguard,vízimentő,-1.301205,救生员,-1.576471,True,0.275266
8,accountant,könyvelő,0.710843,会计,0.635294,True,0.075549
9,student,diák,0.000000,学生,-0.035294,False,0.035294
10,chef,szakács,-1.024096,厨师,-1.047059,True,0.022962
11,programmer,programozó,-1.277108,程序员,-1.270588,True,-0.006520
12,judge,bíró,-0.397590,法官,-0.388235,True,-0.009355
13,security guard,biztonsági őr,-1.771084,保安,-1.752941,True,-0.018143
14,architect,építész,-1.156627,建筑师,-1.117647,True,-0.038979
15,police officer,rendőr,-1.084337,警察,-1.035294,True,-0.049043
16,scientist,tudós,-0.674699,科学家,-0.564706,True,-0.109993
17,engineer,mérnök,-1.108434,工程师,-0.976471,True,-0.131963
18,director,rendező,-0.855422,导演,-0.682353,True,-0.173069
19,prosecutor,ügyész,-0.650602,检察官,-0.458824,True,-0.191779
20,cashier,pénztáros,0.903614,收银员,1.129412,True,-0.225797
21,manager,menedzser,-0.746988,高管,-0.517647,True,-0.229341
22,cleaner,takarító,0.987952,保洁,1.223529,True,-0.235578
23,shop assistant,bolti eladó,0.759036,导购员,1.023529,True,-0.264493
24,pilot,pilóta,-1.530120,飞行员,-1.247059,True,-0.283062
25,doctor,orvos,-0.469880,医生,-0.164706,True,-0.305174
26,caregiver,gondozó,0.795181,护工,1.141176,True,-0.345996
27,pathologist,kórboncnok,-0.975904,法医,-0.623529,True,-0.352374
28,firefighter,tűzoltó,-2.144578,消防员,-1.788235,True,-0.356343
29,CEO,vezérigazgató,-1.265060,董事长,-0.882353,True,-0.382707
30,worker,munkás,-1.638554,工人,-1.188235,True,-0.450319
31,gardener,kertész,-0.939759,园丁,-0.470588,True,-0.469171
32,ticket seller,jegyárus,0.253012,售票员,0.800000,True,-0.546988
33,teacher,tanár,0.108434,教师,0.729412,False,-0.620978
34,professor,professzor,-1.000000,教授,-0.341176,True,-0.658824
35,soldier,katona,-1.759036,军人,-1.082353,True,-0.676683
36,receptionist,recepciós,0.674699,前台,1.635294,True,-0.960595
37,farmer,földműves,-1.626506,农民,-0.458824,True,-1.167682
38,nurse,ápoló,0.614458,护士,1.788235,True,-1.173777
39,waiter,pincér,-0.590361,服务员,0.588235,True,-1.178597
40,secretary,titkár,-0.048193,秘书,1.447059,False,-1.495252

### Plot comparison

### Test significance of the differences

In [112]:
# Delete columns from hu: lechat_hu	lechat_hu_std	copilot_hu	copilot_hu_std	chatgpt_hu	chatgpt_hu_std	deepseek_hu	deepseek_hu_std	gemini_hu	gemini_hu_std	lechat_zh	lechat_zh_std	copilot_zh	copilot_zh_std	chatgpt_zh	chatgpt_zh_std	deepseek_zh	deepseek_zh_std	gemini_zh	gemini_zh_std
columns_to_drop_hu = ['mean_hu', 'std_hu', 'p_value_hu', 'significant_hu', 'lechat_hu', 'lechat_hu_std', 'copilot_hu', 'copilot_hu_std', 'chatgpt_hu', 'chatgpt_hu_std', 'deepseek_hu', 'deepseek_hu_std', 'gemini_hu', 'gemini_hu_std', 'lechat_zh', 'lechat_zh_std', 'copilot_zh', 'copilot_zh_std', 'chatgpt_zh', 'chatgpt_zh_std', 'deepseek_zh', 'deepseek_zh_std', 'gemini_zh', 'gemini_zh_std']
columns_to_drop_zh = ['mean_zh', 'std_zh', 'p_value_zh', 'significant_zh','lechat_hu', 'lechat_hu_std', 'copilot_hu', 'copilot_hu_std', 'chatgpt_hu', 'chatgpt_hu_std', 'deepseek_hu', 'deepseek_hu_std', 'gemini_hu', 'gemini_hu_std', 'lechat_zh', 'lechat_zh_std', 'copilot_zh', 'copilot_zh_std', 'chatgpt_zh', 'chatgpt_zh_std', 'deepseek_zh', 'deepseek_zh_std', 'gemini_zh', 'gemini_zh_std']
df_hu_ratings = df_hu.drop(columns=columns_to_drop_hu)
df_zh_ratings = df_zh.drop(columns=columns_to_drop_zh)

# Drop rows of Gender, Age, and Mean Rating from df_hu_ratings and df_zh_ratings
df_hu_ratings = df_hu_ratings[~df_hu_ratings['hu'].isin(['Gender', 'Age', 'Mean Rating'])]
df_zh_ratings = df_zh_ratings[~df_zh_ratings['zh'].isin(['Gender', 'Age', 'Mean Rating'])]

df_hu_ratings.head()

,hu,en,zh,0,1,2,3,4,5,6,...,74,75,76,77,78,79,80,81,82,service
27,nővér,nurse (sister),护士 (2),3,3,2,3,3,3,3,...,2,3,2,1,2,2,3,2,2,NaN
19,kozmetikus,beautician,美容师,2,3,2,3,2,2,2,...,0,3,2,1,3,3,2,3,3,NaN
15,házvezető,housekeeper,家政员,1,2,0,3,2,2,1,...,1,2,2,0,-1,1,2,3,-3,NaN
22,légiutas-kísérő,flight attendant,乘务员,1,2,1,3,0,2,2,...,1,2,2,0,2,1,1,2,3,NaN
2,HR-es,HR personnel,人事,0,1,0,2,0,1,1,...,0,1,2,0,2,1,2,2,1,NaN

In [113]:
df_hu_ratings

,hu,en,zh,0,1,2,3,4,5,6,...,74,75,76,77,78,79,80,81,82,service
27,nővér,nurse (sister),护士 (2),3,3,2,3,3,3,3,...,2,3,2,1,2,2,3,2,2,NaN
19,kozmetikus,beautician,美容师,2,3,2,3,2,2,2,...,0,3,2,1,3,3,2,3,3,NaN
15,házvezető,housekeeper,家政员,1,2,0,3,2,2,1,...,1,2,2,0,-1,1,2,3,-3,NaN
22,légiutas-kísérő,flight attendant,乘务员,1,2,1,3,0,2,2,...,1,2,2,0,2,1,1,2,3,NaN
2,HR-es,HR personnel,人事,0,1,0,2,0,1,1,...,0,1,2,0,2,1,2,2,1,NaN
24,modell,model,模特,2,2,0,2,0,2,2,...,-1,1,1,0,2,1,1,2,2,NaN
38,takarító,cleaner,保洁,1,2,0,3,0,1,-1,...,0,2,2,0,1,1,-3,-1,-3,NaN
12,fodrász,hairdresser,理发师,0,1,0,0,0,1,1,...,0,1,2,0,1,1,1,2,2,NaN
33,pénztáros,cashier,收银员,1,2,0,2,0,2,1,...,0,2,0,0,2,1,1,1,1,NaN
14,gondozó,caregiver,护工,0,2,0,3,0,2,-1,...,0,2,0,0,-1,1,-1,-1,0,NaN
9,dietetikus,dietitian,营养师,0,0,0,1,0,1,2,...,0,1,0,0,1,0,1,1,2,NaN
7,bolti eladó,shop assistant,导购员,1,2,0,2,0,1,1,...,0,2,0,0,1,0,1,1,1,NaN
21,könyvelő,accountant,会计,1,0,0,2,0,1,-1,...,1,1,1,0,0,1,1,1,0,NaN
34,recepciós,receptionist,前台,0,1,0,2,0,0,1,...,0,2,0,0,1,0,1,1,1,NaN
45,ápoló,nurse,护士,1,0,1,3,-3,0,-1,...,1,2,0,-1,2,-1,2,-1,0,NaN
4,PR munkatárs,PR specialist,公关,0,0,0,1,0,0,1,...,0,1,0,0,1,1,1,0,1,NaN
16,jegyárus,ticket seller,售票员,0,-1,0,2,0,1,0,...,0,2,0,0,0,0,0,0,0,NaN
39,tanár,teacher,教师,0,0,0,2,0,0,-1,...,-1,2,0,0,-1,1,0,0,1,NaN
10,diák,student,学生,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
11,felszolgáló,server,服务员 (2),0,-1,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,NaN
40,titkár,secretary,秘书,0,-2,0,0,1,-1,-1,...,-1,1,0,0,-3,-1,-3,-1,0,NaN
8,bíró,judge,法官,-1,0,0,-1,0,0,-1,...,1,-2,0,0,-1,1,-2,-2,0,NaN
28,orvos,doctor,医生,-1,0,0,-1,0,0,-1,...,0,-1,0,0,-1,-1,-3,-1,0,NaN
30,pincér,waiter,服务员,0,-1,0,1,0,-1,-1,...,0,0,0,0,-1,-1,-3,-1,-3,NaN
47,ügyész,prosecutor,检察官,0,-1,0,-1,0,0,-1,...,0,-3,0,0,-1,-2,0,-2,0,NaN
41,tudós,scientist,科学家,0,-1,0,-1,0,-1,-1,...,0,-2,-1,0,-1,-1,-2,-2,-2,NaN
23,menedzser,manager,高管,-1,0,-1,0,0,0,-1,...,1,-1,0,0,-1,-1,-1,-2,-3,NaN
35,rendező,director,导演,0,-1,0,-1,0,-1,-1,...,0,-2,-1,0,-1,-1,-2,-2,-1,NaN
18,kertész,gardener,园丁,0,0,0,-1,-1,-2,-1,...,0,-3,0,0,0,-1,-1,-2,-3,NaN
20,kórboncnok,pathologist,法医,0,-1,0,-1,-2,-1,-1,...,0,-3,-1,-1,-1,-1,-3,-1,0,NaN
31,professzor,professor,教授,-1,-2,0,-2,0,0,-1,...,0,-2,-2,0,-1,-1,-2,-1,-2,NaN
37,szakács,chef,厨师,0,0,-1,-1,-1,-2,-1,...,-2,-2,-1,-1,0,-1,-2,-2,0,NaN
36,rendőr,police officer,警察,-2,-2,-1,-2,-1,-2,-1,...,0,-2,-1,0,-1,-1,-2,-1,0,NaN
26,mérnök,engineer,工程师,-2,-1,-1,-2,0,0,-1,...,0,-3,-1,0,-1,-1,-2,-3,-3,NaN
46,építész,architect,建筑师,-3,-2,-2,-2,0,-1,-1,...,0,-2,-1,0,-2,1,-2,-3,-2,NaN
43,vezérigazgató,CEO,董事长,-1,-1,-1,-1,0,-1,-1,...,0,-3,0,-1,-2,-2,-1,-2,-1,NaN
32,programozó,programmer,程序员,-1,-2,0,-2,-2,-2,-1,...,0,-3,-1,0,-1,-1,-3,-2,-3,NaN
44,vízimentő,lifeguard,救生员,-1,-2,0,0,0,-2,-1,...,0,-3,-1,-1,-1,-1,-3,-2,-1,NaN
29,pilóta,pilot,飞行员,-1,-2,0,-2,-1,-2,-1,...,0,-3,-1,0,-2,-2,-2,-1,-2,NaN
13,földműves,farmer,农民,-1,-2,-2,-1,-1,-1,-2,...,-2,-3,-2,0,-1,-1,-2,-1,-3,NaN
25,munkás,worker,工人,0,-2,-2,-1,0,-1,-1,...,0,-3,-2,-1,-2,-2,-3,-1,-3,NaN
17,katona,soldier,军人,-3,-2,-2,-2,-2,-2,-2,...,-1,-2,-2,-1,-2,-2,-2,-2,-2,NaN
6,biztonsági őr,security guard,保安,-2,-2,-2,-2,-1,-2,-2,...,-1,-3,-1,0,-1,-2,-3,-2,-3,NaN
42,tűzoltó,firefighter,消防员,-2,-3,0,-2,-2,-3,-2,...,-1,-3,-2,-1,-2,-2,-3,-3,-3,NaN
5,Participant,NaN,NaN,1,2,3,4,5,6,7,...,87,88,89,90,93,95,96,97,99,NaN

In [114]:
# This didn't work
# Change "服务员 (2)" to "服务员" in zh column
df_hu.loc[df_hu['zh'] == '服务员 (2)', 'zh'] = '服务员'
df_zh.loc[df_zh['zh'] == '服务员 (2)', 'zh'] = '服务员'

df_hu_ratings.loc[df_hu_ratings['zh'] == '服务员 (2)', 'zh'] = '服务员'
df_zh_ratings.loc[df_zh_ratings['zh'] == '服务员 (2)', 'zh'] = '服务员'

# Change "护士 (2)(2)" to "护士" in zh column
# df_hu.loc[df_hu['zh'] == '护士 (2)(2)', 'zh'] = '护士'
# df_zh.loc[df_zh['zh'] == '护士 (2)(2)', 'zh'] = '护士'

# df_hu_ratings.loc[df_hu_ratings['zh'] == '护士 (2)(2)', 'zh'] = '护士'
# df_zh_ratings.loc[df_zh_ratings['zh'] == '护士 (2)(2)', 'zh'] = '护士'

df_hu.loc[df_hu['zh'] == '服务员']
df_hu_ratings.loc[df_hu_ratings['zh'] == '服务员']

,hu,en,zh,0,1,2,3,4,5,6,...,74,75,76,77,78,79,80,81,82,service
11,felszolgáló,server,服务员,0,-1,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,NaN
30,pincér,waiter,服务员,0,-1,0,1,0,-1,-1,...,0,0,0,0,-1,-1,-3,-1,-3,NaN

In [124]:
# Get a list of occupation in English that are common in both Hungarian and Chinese datasets
common_en = sorted(
    set(df_hu['en'].dropna())
    .intersection(df_zh['en'].dropna())
)
common_en

# Print length of common_en
print(f"Number of common English occupations: {len(common_en)}")


results = []

for en_name in common_en:
    # Get the occupation row for each language
    hu_row = df_hu_ratings[df_hu_ratings['en'] == en_name]
    zh_row = df_zh_ratings[df_zh_ratings['en'] == en_name]
    
    # Get raw ratings (drop non-numeric columns)
    hu_ratings = hu_row.drop(columns=['en', 'hu', 'zh'], errors='ignore').values.flatten()
    zh_ratings = zh_row.drop(columns=['en', 'hu', 'zh'], errors='ignore').values.flatten()
    
    # Remove NaNs and convert to float
    hu_ratings = pd.to_numeric(pd.Series(hu_ratings).dropna(), errors='coerce')
    zh_ratings = pd.to_numeric(pd.Series(zh_ratings).dropna(), errors='coerce')
    
    # Calculate means
    mean_hu = hu_ratings.mean()
    mean_zh = zh_ratings.mean()
    diff = mean_hu - mean_zh
    
    # Perform t-test
    t_stat, p_value = ttest_ind(hu_ratings, zh_ratings, equal_var=False)
    print(f"Processing {en_name}: hu mean={mean_hu:.2f}, zh mean={mean_zh:.2f}, diff={diff:.2f}, t_stat={t_stat:.2f}, p_value={p_value:.4g}")
    
    results.append({
        'en': en_name,
        'hu': hu_row['hu'].values[0] if not hu_row.empty else None,
        'zh': zh_row['zh'].values[0] if not zh_row.empty else None,
        'mean_hu': mean_hu,
        'mean_zh': mean_zh,
        'mean_difference': diff,
        't_stat': t_stat,
        'p_value': p_value,
        'very_highly_significant': p_value is not None and p_value < 0.001,
        'highly_significant': p_value is not None and 0.001 <= p_value < 0.01,
        'significant': p_value is not None and 0.01 <= p_value < 0.05,
        # 'marginally_significant': p_value is not None and 0.05 < p_value < 0.1
    })

# Create a DataFrame from the results
df_plot = pd.DataFrame(results)

# Create axis labels: bold for significant*, bold+ for marginally significant+
def occupation_label(row):
    label = row['en']
    if row['very_highly_significant']:
        label = f"<b>{label}***</b>"
    if row['highly_significant']:
        label = f"<b>{label}**</b>"
    if row['significant']:
        label = f"<b>{label}*</b>"
    # elif row['marginally_significant']:
    #     label = f"<b>{label}+</b>"
    return label

df_plot['en_label'] = df_plot.apply(occupation_label, axis=1)

# Sort by the mean average
df_plot['mean_avg'] = (df_plot['mean_hu'] + df_plot['mean_zh']) / 2
df_plot = df_plot.sort_values('mean_avg', ascending=False)

fig = go.Figure()

fig.add_trace(go.Bar(
    x = df_plot['en_label'],
    y = df_plot['mean_hu'],
    name = 'Hungarian',
    marker_color = hungarian_color,
    hovertemplate = 'Hungarian: %{customdata[0]}<br>Mean: %{y:.2f}<br>p-value: %{customdata[1]:.4g}',
    customdata=df_plot[['hu', 'p_value']]
))

fig.add_trace(go.Bar(
    x = df_plot['en_label'],
    y = df_plot['mean_zh'],
    name = 'Chinese',
    marker_color = chinese_color,
    hovertemplate = 'Chinese: %{customdata[0]}<br>Mean: %{y:.2f}<br>p-value: %{customdata[1]:.4g}',
    customdata = df_plot[['zh', 'p_value']]
))

fig.update_layout(
    barmode='group',
    template='plotly_white',
    margin=dict(l=0, r=0, t=20, b=80),  # extra bottom space for legend note
    font = dict(family="Times New Roman, serif", size=16, color='black'),
    xaxis_title='',
    xaxis_tickangle=-45,
    yaxis_title='Mean Rating (Bias)',
    yaxis=dict(
        range=[-3.05, 3.05],
        tickvals=[-3, -2, -1, 0, 1, 2, 3],
        ),
    legend=dict(
        orientation='h',
        yanchor='top',
        y=1,
        xanchor='center',
        x=0.5,
        bgcolor='rgba(220, 220, 220, 0.25)',
        ),
    annotations=[
        dict(
            text="Significance: * p<0.05, ** p<0.01, *** p<0.001",
            x=0.5, y=0, xref='paper', yref='paper',
            showarrow=False, align='center', font=dict(size=12, color='black')
        )
    ]
)

# Show the plot
fig.show()

# Save as html and image
fig.write_html('occupations_comparison.html')
fig.write_image('occupations_comparison.png', scale=3, width=1000, height=400)

Number of common English occupations: 41
Processing CEO: hu mean=-1.27, zh mean=-0.88, diff=-0.38, t_stat=-2.95, p_value=0.003609
Processing HR personnel: hu mean=1.19, zh mean=0.66, diff=0.53, t_stat=3.97, p_value=0.0001066
Processing accountant: hu mean=0.71, zh mean=0.64, diff=0.08, t_stat=0.59, p_value=0.5538
Processing architect: hu mean=-1.16, zh mean=-1.12, diff=-0.04, t_stat=-0.27, p_value=0.7909
Processing beautician: hu mean=2.12, zh mean=1.67, diff=0.45, t_stat=3.32, p_value=0.001102
Processing caregiver: hu mean=0.80, zh mean=1.14, diff=-0.35, t_stat=-2.08, p_value=0.03876
Processing cashier: hu mean=0.90, zh mean=1.13, diff=-0.23, t_stat=-1.73, p_value=0.08573
Processing chef: hu mean=-1.02, zh mean=-1.05, diff=0.02, t_stat=0.18, p_value=0.8599
Processing cleaner: hu mean=0.99, zh mean=1.22, diff=-0.24, t_stat=-1.36, p_value=0.1768
Processing dietitian: hu mean=0.77, zh mean=0.44, diff=0.34, t_stat=2.73, p_value=0.006995
Processing director: hu mean=-0.86, zh mean=-0.68, diff=-0.17, t_stat=-1.35, p_value=0.1789
Processing doctor: hu mean=-0.47, zh mean=-0.16, diff=-0.31, t_stat=-2.87, p_value=0.004582
Processing engineer: hu mean=-1.11, zh mean=-0.98, diff=-0.13, t_stat=-0.97, p_value=0.3358
Processing farmer: hu mean=-1.63, zh mean=-0.46, diff=-1.17, t_stat=-8.38, p_value=3.052e-14
Processing firefighter: hu mean=-2.14, zh mean=-1.79, diff=-0.36, t_stat=-2.58, p_value=0.01061
Processing flight attendant: hu mean=1.36, zh mean=0.85, diff=0.51, t_stat=3.57, p_value=0.0004686
Processing gardener: hu mean=-0.94, zh mean=-0.47, diff=-0.47, t_stat=-3.31, p_value=0.001157
Processing hairdresser: hu mean=0.92, zh mean=-0.64, diff=1.55, t_stat=12.22, p_value=7.129e-25
Processing housekeeper: hu mean=1.60, zh mean=1.01, diff=0.59, t_stat=3.65, p_value=0.0003556
Processing judge: hu mean=-0.40, zh mean=-0.39, diff=-0.01, t_stat=-0.07, p_value=0.9434
Processing lifeguard: hu mean=-1.30, zh mean=-1.58, diff=0.28, t_stat=1.96, p_value=0.05147
Processing manager: hu mean=-0.75, zh mean=-0.52, diff=-0.23, t_stat=-1.74, p_value=0.08414
Processing model: hu mean=1.08, zh mean=0.75, diff=0.33, t_stat=2.46, p_value=0.01493
Processing nurse: hu mean=0.61, zh mean=1.79, diff=-1.17, t_stat=-8.00, p_value=8.734e-13
Processing pathologist: hu mean=-0.98, zh mean=-0.62, diff=-0.35, t_stat=-2.42, p_value=0.01681
Processing pilot: hu mean=-1.53, zh mean=-1.25, diff=-0.28, t_stat=-2.20, p_value=0.02931
Processing police officer: hu mean=-1.08, zh mean=-1.04, diff=-0.05, t_stat=-0.41, p_value=0.6799
Processing professor: hu mean=-1.00, zh mean=-0.34, diff=-0.66, t_stat=-5.25, p_value=5.318e-07
Processing programmer: hu mean=-1.28, zh mean=-1.27, diff=-0.01, t_stat=-0.05, p_value=0.9611
Processing prosecutor: hu mean=-0.65, zh mean=-0.46, diff=-0.19, t_stat=-1.48, p_value=0.1396
Processing receptionist: hu mean=0.67, zh mean=1.64, diff=-0.96, t_stat=-7.79, p_value=6.789e-13
Processing scientist: hu mean=-0.67, zh mean=-0.56, diff=-0.11, t_stat=-0.89, p_value=0.3726
Processing secretary: hu mean=-0.05, zh mean=1.45, diff=-1.50, t_stat=-8.16, p_value=4.182e-13
Processing security guard: hu mean=-1.77, zh mean=-1.75, diff=-0.02, t_stat=-0.14, p_value=0.8924
Processing shop assistant: hu mean=0.76, zh mean=1.02, diff=-0.26, t_stat=-1.99, p_value=0.04862
Processing soldier: hu mean=-1.76, zh mean=-1.08, diff=-0.68, t_stat=-5.90, p_value=1.999e-08
Processing student: hu mean=0.00, zh mean=-0.04, diff=0.04, t_stat=0.76, p_value=0.4467
Processing teacher: hu mean=0.11, zh mean=0.73, diff=-0.62, t_stat=-4.36, p_value=2.35e-05
Processing ticket seller: hu mean=0.25, zh mean=0.80, diff=-0.55, t_stat=-4.37, p_value=2.194e-05
Processing waiter: hu mean=-0.59, zh mean=0.59, diff=-1.18, t_stat=-8.21, p_value=8.594e-14
Processing worker: hu mean=-1.64, zh mean=-1.19, diff=-0.45, t_stat=-2.95, p_value=0.00366

#### Significant differences

In [116]:
# Show rows in the df_plot where significant column is true
print("Significant differences between Hungarian and Chinese ratings:")
significant = df_plot[df_plot['significant']][['en', 'hu', 'zh', 'mean_hu', 'mean_zh', 'mean_difference', 't_stat', 'p_value']]

# Count and print rows with significant differences
print(f"Number of significant differences: {len(significant)}")

# Sort this by p-value
significant = significant.sort_values('p_value')
significant

Significant differences between Hungarian and Chinese ratings:
Number of significant differences: 6

,en,hu,zh,mean_hu,mean_zh,mean_difference,t_stat,p_value
14,firefighter,tűzoltó,消防员,-2.144578,-1.788235,-0.356343,-2.584753,0.010606
22,model,modell,模特,1.084337,0.752941,0.331396,2.459971,0.014934
24,pathologist,kórboncnok,法医,-0.975904,-0.623529,-0.352374,-2.415664,0.016814
25,pilot,pilóta,飞行员,-1.530120,-1.247059,-0.283062,-2.200449,0.029315
5,caregiver,gondozó,护工,0.795181,1.141176,-0.345996,-2.083495,0.038759
34,shop assistant,bolti eladó,导购员,0.759036,1.023529,-0.264493,-1.986869,0.048624

In [117]:
# Create a DataFrame for comparison of occupations in both languages
df_comparison = df_plot[['en', 'hu', 'zh', 'mean_hu', 'mean_zh', 'mean_difference', 't_stat', 'p_value', 'significant',]].copy()

# Save the comparison DataFrame to an Excel file
df_comparison.to_excel('occupations_comparison.xlsx', index=False)

In [118]:
# Prepare comparison DataFrame for occupations present in both datasets
df_compare = df_hu[df_hu['en'].isin(in_both)][['en', 'mean_hu', 'hu']].merge(
    df_zh[df_zh['en'].isin(in_both)][['en', 'mean_zh', 'zh']], on='en', suffixes=('_hu', '_zh'))

# Sort by the average of the two means for better visualization
df_compare['mean_avg'] = (df_compare['mean_hu'] + df_compare['mean_zh']) / 2
df_compare = df_compare.sort_values('mean_avg', ascending=False)

# Add a new column 'bias' considering absolute values: 
# 'Hungarian' if abs(mean_hu) > abs(mean_zh), 'Chinese' if abs(mean_hu) < abs(mean_zh), 'Equal' if they are the same
df_compare['bias'] = df_compare.apply(
    lambda row: 'Hungarian' if abs(row['mean_hu']) > abs(row['mean_zh']) 
    else ('Chinese' if abs(row['mean_hu']) < abs(row['mean_zh']) else 'Equal'), axis=1
)

# Count values in 'bias' column and print the results
bias_counts = df_compare['bias'].value_counts()
print("Bias counts:")
print(bias_counts)

# Plot this
fig = px.bar(
    bias_counts,
    x=bias_counts.index,
    y=bias_counts.values,
    # title='Count of more bias per occupation',
    labels={'x': 'Bias', 'y': 'Count'},
    color=bias_counts.index,
    color_discrete_map={'Hungarian': hungarian_color, 'Chinese': chinese_color, 'Equal': neutral_color}
)
fig.update_layout(
    xaxis_title='Bias',
    yaxis_title='Count',
    template='plotly_white',
    font=dict(family="Times New Roman, serif", size=32, color='black'),
    margin=dict(l=0, r=0, t=0, b=0),
    width=900,
    height=400,
    # showlegend=False
)
fig.show()

# Save the figure
fig.write_image('bias_counts.png', scale=3, width=900, height=400)

Bias counts:
bias
Hungarian    29
Chinese      12
Name: count, dtype: int64

### CLMM prep

In [119]:
# Merge Hungarian and Chinese dataframes for CLMM analysis
df_clmm = pd.concat([df_hu_clmm, df_zh_clmm], ignore_index=True)

# Drop Item column and rename Occupation to Item
df_clmm = df_clmm.drop(columns=['Item']).rename(columns={'Occupation': 'Item'})

# rename ID to Participant
df_clmm = df_clmm.rename(columns={'ID': 'Participant'})

# Reorder columns to: Item, Language, Participant, Gender, Age, Rating.
df_clmm = df_clmm[['Item', 'Language', 'Participant', 'Gender', 'Age', 'Rating']]

# Change male to men and female to women in Gender
# df_clmm['Gender'] = df_clmm['Gender'].replace({'male': 'men', 'female': 'women'})

# Export this as a csv
df_clmm.to_csv('ratings.csv', index=False)
df_clmm

           Item   Language Participant Participant Gender    Age  Rating
0         model  Hungarian        hu_1         NaN   male  25-35       2
1         model  Hungarian        hu_2         NaN   male  45-55       2
2         model  Hungarian        hu_3         NaN   male  25-35       0
3         model  Hungarian        hu_4         NaN   male  35-45       2
4         model  Hungarian        hu_5         NaN   male  25-35       0
...         ...        ...         ...         ...    ...    ...     ...
7387  architect    Chinese         NaN       zh_81   male    <25      -2
7388  architect    Chinese         NaN       zh_82   male  25-35      -3
7389  architect    Chinese         NaN       zh_83   male  35-45       0
7390  architect    Chinese         NaN       zh_84   male    <25      -2
7391  architect    Chinese         NaN       zh_85   male  45-55      -1

[7392 rows x 7 columns]

In [120]:
# Per-item mean by language
item_means = (
    df_clmm.groupby(['Item', 'Language'])['Rating']
    .mean()
    .unstack('Language')
    .reindex(columns=['Hungarian', 'Chinese'])
)

# Classify items where both languages agree on direction
def classify_bias(row):
    hu, zh = row['Hungarian'], row['Chinese']
    if pd.isna(hu) or pd.isna(zh):
        return np.nan
    if hu > 0 and zh > 0:
        return 'female'
    if hu < 0 and zh < 0:
        return 'male'
    return np.nan  # change to 'mixed' if you prefer a label instead of NaN

bias_map = item_means.apply(classify_bias, axis=1)

# Add per-item bias back to all rows
df_clmm['Bias'] = df_clmm['Item'].map(bias_map)

# Optional: inspect result
df_clmm[['Item', 'Language', 'Rating', 'Bias']]

# Drop rows where Item is missing
df_clmm = df_clmm.dropna(subset=['Bias'])

# Export this as a csv
df_clmm.to_csv('ratings_with_bias.csv', index=False)